/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.mydsl.lts;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Column Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.lts.ColumnRef#getTable <em>Table</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.lts.ColumnRef#getColumn <em>Column</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.lts.LtsPackage#getColumnRef()
 * @model
 * @generated
 */
public interface ColumnRef extends PrimaryExpression
{
  /**
   * Returns the value of the '<em><b>Table</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' attribute.
   * @see #setTable(String)
   * @see org.xtext.example.mydsl.lts.LtsPackage#getColumnRef_Table()
   * @model
   * @generated
   */
  String getTable();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.lts.ColumnRef#getTable <em>Table</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table</em>' attribute.
   * @see #getTable()
   * @generated
   */
  void setTable(String value);

  /**
   * Returns the value of the '<em><b>Column</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column</em>' attribute.
   * @see #setColumn(String)
   * @see org.xtext.example.mydsl.lts.LtsPackage#getColumnRef_Column()
   * @model
   * @generated
   */
  String getColumn();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.lts.ColumnRef#getColumn <em>Column</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Column</em>' attribute.
   * @see #getColumn()
   * @generated
   */
  void setColumn(String value);

} // ColumnRef
