/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.mydsl.lts;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.lts.LtsProcess#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.lts.LtsProcess#getDataSources <em>Data Sources</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.lts.LtsProcess#getTables <em>Tables</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.lts.LtsProcess#getOperations <em>Operations</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.lts.LtsProcess#getOutput <em>Output</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.lts.LtsPackage#getLtsProcess()
 * @model
 * @generated
 */
public interface LtsProcess extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.lts.LtsPackage#getLtsProcess_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.lts.LtsProcess#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Data Sources</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.lts.DataSource}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Sources</em>' containment reference list.
   * @see org.xtext.example.mydsl.lts.LtsPackage#getLtsProcess_DataSources()
   * @model containment="true"
   * @generated
   */
  EList<DataSource> getDataSources();

  /**
   * Returns the value of the '<em><b>Tables</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.lts.Table}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tables</em>' containment reference list.
   * @see org.xtext.example.mydsl.lts.LtsPackage#getLtsProcess_Tables()
   * @model containment="true"
   * @generated
   */
  EList<Table> getTables();

  /**
   * Returns the value of the '<em><b>Operations</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operations</em>' containment reference.
   * @see #setOperations(Operations)
   * @see org.xtext.example.mydsl.lts.LtsPackage#getLtsProcess_Operations()
   * @model containment="true"
   * @generated
   */
  Operations getOperations();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.lts.LtsProcess#getOperations <em>Operations</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operations</em>' containment reference.
   * @see #getOperations()
   * @generated
   */
  void setOperations(Operations value);

  /**
   * Returns the value of the '<em><b>Output</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output</em>' containment reference.
   * @see #setOutput(Output)
   * @see org.xtext.example.mydsl.lts.LtsPackage#getLtsProcess_Output()
   * @model containment="true"
   * @generated
   */
  Output getOutput();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.lts.LtsProcess#getOutput <em>Output</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Output</em>' containment reference.
   * @see #getOutput()
   * @generated
   */
  void setOutput(Output value);

} // LtsProcess
