/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.mydsl.lts;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sort Column</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.lts.SortColumn#getColumnName <em>Column Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.lts.SortColumn#getOrder <em>Order</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.lts.LtsPackage#getSortColumn()
 * @model
 * @generated
 */
public interface SortColumn extends EObject
{
  /**
   * Returns the value of the '<em><b>Column Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column Name</em>' attribute.
   * @see #setColumnName(String)
   * @see org.xtext.example.mydsl.lts.LtsPackage#getSortColumn_ColumnName()
   * @model
   * @generated
   */
  String getColumnName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.lts.SortColumn#getColumnName <em>Column Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Column Name</em>' attribute.
   * @see #getColumnName()
   * @generated
   */
  void setColumnName(String value);

  /**
   * Returns the value of the '<em><b>Order</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Order</em>' attribute.
   * @see #setOrder(String)
   * @see org.xtext.example.mydsl.lts.LtsPackage#getSortColumn_Order()
   * @model
   * @generated
   */
  String getOrder();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.lts.SortColumn#getOrder <em>Order</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Order</em>' attribute.
   * @see #getOrder()
   * @generated
   */
  void setOrder(String value);

} // SortColumn
