package program.src.main.java.org.enorm.domain.steps.joinStep;

/*Generated by MPS */


public class FactoryJoinStep {
  private static IJoinStep step;

  public static void setStep(IJoinStep s) {
    step = s;
  }

  public static IJoinStep getStep() {
    return step;
  }

}
