/* Generated by Xtext. */
package org.example.lts


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class LtsRuntimeModule extends AbstractLtsRuntimeModule {
}
