package ltsdsl.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.scope.ListScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.ArrayList;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.Sequence;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SProperty;

public class Lookup_Constraints extends BaseConstraintsDescriptor {
  public Lookup_Constraints() {
    super(CONCEPTS.Lookup$Sc);
  }

  @Override
  protected Map<SReferenceLink, ReferenceConstraintsDescriptor> getSpecifiedReferences() {
    BaseReferenceConstraintsDescriptor d0 = new BaseReferenceConstraintsDescriptor(LINKS.column$fpCr, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:7544216e-c3d5-4a4d-a97b-6a83591122eb(ltsdsl.constraints)", "6905902123112595384");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            return ListScope.forNamedElements(SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.table$fimW), LINKS.columns$_HNP));
          }
        };
      }
    };
    BaseReferenceConstraintsDescriptor d1 = new BaseReferenceConstraintsDescriptor(LINKS.operandColumn$fr2x, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:7544216e-c3d5-4a4d-a97b-6a83591122eb(ltsdsl.constraints)", "6905902123112602308");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            return ListScope.forNamedElements(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.table$fimW), LINKS.columns$_HNP)).where((it) -> it != SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.column$fpCr)));
          }
        };
      }
    };
    BaseReferenceConstraintsDescriptor d2 = new BaseReferenceConstraintsDescriptor(LINKS.matchColumn$fq6t, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:7544216e-c3d5-4a4d-a97b-6a83591122eb(ltsdsl.constraints)", "6905902123112648561");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            if (SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.table$fimW) == SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.lookupTable$fj3Z)) {
              List<SNode> scope = new ArrayList<SNode>();
              ListSequence.fromList(scope).addElement(SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.column$fpCr));
              return ListScope.forNamedElements(scope);
            }
            return ListScope.forNamedElements(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.lookupTable$fj3Z), LINKS.columns$_HNP)).where((it) -> SPropertyOperations.getEnum(it, PROPS.dataType$Xb6z).equals(SPropertyOperations.getEnum(SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.column$fpCr), PROPS.dataType$Xb6z))));

          }
        };
      }
    };
    BaseReferenceConstraintsDescriptor d3 = new BaseReferenceConstraintsDescriptor(LINKS.lookupColumn$fwTU, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:7544216e-c3d5-4a4d-a97b-6a83591122eb(ltsdsl.constraints)", "6905902123112651060");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            if (SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.table$fimW) == SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.lookupTable$fj3Z)) {
              return ListScope.forNamedElements(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.lookupTable$fj3Z), LINKS.columns$_HNP)).where((it) -> it != SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.matchColumn$fq6t) && SPropertyOperations.getEnum(it, PROPS.dataType$Xb6z).equals(SPropertyOperations.getEnum(SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.operandColumn$fr2x), PROPS.dataType$Xb6z)) && it != SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.operandColumn$fr2x)));

            }
            return ListScope.forNamedElements(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.lookupTable$fj3Z), LINKS.columns$_HNP)).where((it) -> it != SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.matchColumn$fq6t) && SPropertyOperations.getEnum(it, PROPS.dataType$Xb6z).equals(SPropertyOperations.getEnum(SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.operandColumn$fr2x), PROPS.dataType$Xb6z))));

          }
        };
      }
    };
    BaseReferenceConstraintsDescriptor d4 = new BaseReferenceConstraintsDescriptor(LINKS.resultTable$fRcp, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:7544216e-c3d5-4a4d-a97b-6a83591122eb(ltsdsl.constraints)", "7550318198638238410");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            Scope defaultScope = _context.getScopeEvaluationContext().ofNodesDefault(_context.getModel(), CONCEPTS.Table$$W);

            if (SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.table$fimW) != SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.lookupTable$fj3Z)) {
              return ListScope.forNamedElements(Sequence.fromIterable(defaultScope.getAvailableElements(null)).where((it) -> it != SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.lookupTable$fj3Z)));
            }

            return ListScope.forNamedElements(defaultScope.getAvailableElements(null));

          }
        };
      }
    };
    BaseReferenceConstraintsDescriptor d5 = new BaseReferenceConstraintsDescriptor(LINKS.resultColumn$fyk0, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:7544216e-c3d5-4a4d-a97b-6a83591122eb(ltsdsl.constraints)", "6905902123112702876");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            return ListScope.forNamedElements(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.resultTable$fRcp), LINKS.columns$_HNP)).where((it) -> SPropertyOperations.getEnum(it, PROPS.dataType$Xb6z).equals(SPropertyOperations.getEnum(SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.operandColumn$fr2x), PROPS.dataType$Xb6z)) && it != SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.column$fpCr) && it != SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.matchColumn$fq6t) && it != SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.operandColumn$fr2x) && it != SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.lookupColumn$fwTU)));
          }
        };
      }
    };
    Map<SReferenceLink, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLink, ReferenceConstraintsDescriptor>();
    references.put(d0.getReference(), d0);
    references.put(d1.getReference(), d1);
    references.put(d2.getReference(), d2);
    references.put(d3.getReference(), d3);
    references.put(d4.getReference(), d4);
    references.put(d5.getReference(), d5);
    return references;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Lookup$Sc = MetaAdapterFactory.getConcept(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x5fd6b16455bdff26L, "ltsdsl.structure.Lookup");
    /*package*/ static final SConcept Table$$W = MetaAdapterFactory.getConcept(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5720c3a0cL, "ltsdsl.structure.Table");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink column$fpCr = MetaAdapterFactory.getReferenceLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x5fd6b16455bdff26L, 0x5fd6b16455bdff34L, "column");
    /*package*/ static final SReferenceLink table$fimW = MetaAdapterFactory.getReferenceLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x5fd6b16455bdff26L, 0x5fd6b16455bdff2aL, "table");
    /*package*/ static final SContainmentLink columns$_HNP = MetaAdapterFactory.getContainmentLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5720c3a0cL, 0x3fa6e5f5720ca3a7L, "columns");
    /*package*/ static final SReferenceLink operandColumn$fr2x = MetaAdapterFactory.getReferenceLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x5fd6b16455bdff26L, 0x5fd6b16455bdff3aL, "operandColumn");
    /*package*/ static final SReferenceLink matchColumn$fq6t = MetaAdapterFactory.getReferenceLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x5fd6b16455bdff26L, 0x5fd6b16455bdff36L, "matchColumn");
    /*package*/ static final SReferenceLink lookupTable$fj3Z = MetaAdapterFactory.getReferenceLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x5fd6b16455bdff26L, 0x5fd6b16455bdff2dL, "lookupTable");
    /*package*/ static final SReferenceLink lookupColumn$fwTU = MetaAdapterFactory.getReferenceLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x5fd6b16455bdff26L, 0x5fd6b16455bdff3eL, "lookupColumn");
    /*package*/ static final SReferenceLink resultTable$fRcp = MetaAdapterFactory.getReferenceLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x5fd6b16455bdff26L, 0x5fd6b16455bdff5eL, "resultTable");
    /*package*/ static final SReferenceLink resultColumn$fyk0 = MetaAdapterFactory.getReferenceLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x5fd6b16455bdff26L, 0x5fd6b16455bdff44L, "resultColumn");
  }

  private static final class PROPS {
    /*package*/ static final SProperty dataType$Xb6z = MetaAdapterFactory.getProperty(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5720c3a0fL, 0x3fa6e5f5720c3a1aL, "dataType");
  }
}
