package ltsdsl.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.scope.ListScope;
import jetbrains.mps.internal.collections.runtime.Sequence;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class Sort_Constraints extends BaseConstraintsDescriptor {
  public Sort_Constraints() {
    super(CONCEPTS.Sort$km);
  }

  @Override
  protected Map<SReferenceLink, ReferenceConstraintsDescriptor> getSpecifiedReferences() {
    BaseReferenceConstraintsDescriptor d0 = new BaseReferenceConstraintsDescriptor(LINKS.column$7r2_, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:7544216e-c3d5-4a4d-a97b-6a83591122eb(ltsdsl.constraints)", "2876302107890074460");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            Scope defaultScope = _context.getScopeEvaluationContext().ofNodesDefault(_context.getModel(), CONCEPTS.Column$Ap);
            final Iterable<SNode> tableColumns = SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.table$7qN$), LINKS.columns$_HNP);

            return ListScope.forNamedElements(Sequence.fromIterable(defaultScope.getAvailableElements(null)).where((it) -> Sequence.fromIterable(tableColumns).contains(it)));
          }
        };
      }
    };
    Map<SReferenceLink, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLink, ReferenceConstraintsDescriptor>();
    references.put(d0.getReference(), d0);
    return references;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Sort$km = MetaAdapterFactory.getConcept(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f57213f4f4L, "ltsdsl.structure.Sort");
    /*package*/ static final SConcept Column$Ap = MetaAdapterFactory.getConcept(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5720c3a0fL, "ltsdsl.structure.Column");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink column$7r2_ = MetaAdapterFactory.getReferenceLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f57213f4f4L, 0x3fa6e5f57213f4f6L, "column");
    /*package*/ static final SReferenceLink table$7qN$ = MetaAdapterFactory.getReferenceLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f57213f4f4L, 0x3fa6e5f57213f4f5L, "table");
    /*package*/ static final SContainmentLink columns$_HNP = MetaAdapterFactory.getContainmentLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5720c3a0cL, 0x3fa6e5f5720ca3a7L, "columns");
  }
}
