package ltsdsl.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.scope.ListScope;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TableToSave_Constraints extends BaseConstraintsDescriptor {
  public TableToSave_Constraints() {
    super(CONCEPTS.TableToSave$d1);
  }

  @Override
  protected Map<SReferenceLink, ReferenceConstraintsDescriptor> getSpecifiedReferences() {
    BaseReferenceConstraintsDescriptor d0 = new BaseReferenceConstraintsDescriptor(LINKS.table$LR94, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:7544216e-c3d5-4a4d-a97b-6a83591122eb(ltsdsl.constraints)", "5891918328305159821");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            Scope defaultScope = _context.getScopeEvaluationContext().ofNodesDefault(_context.getModel(), CONCEPTS.Table$$W);
            List<SNode> inScopeTables = Sequence.fromIterable(defaultScope.getAvailableElements(null)).toList();
            Scope toCompareScope = _context.getScopeEvaluationContext().ofNodesDefault(_context.getModel(), CONCEPTS.TableToSave$d1);
            List<SNode> tableToSaveNodes = Sequence.fromIterable(toCompareScope.getAvailableElements(null)).toList();

            // remove already referenced columns
            for (SNode n : tableToSaveNodes) {
              SNode t = (SNode) n;
              if (_context.getReferenceNode() != t) {
                ListSequence.fromList(inScopeTables).removeElement(SLinkOperations.getTarget(t, LINKS.table$LR94));
              }
            }

            return ListScope.forNamedElements(inScopeTables);
          }
        };
      }
    };
    Map<SReferenceLink, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLink, ReferenceConstraintsDescriptor>();
    references.put(d0.getReference(), d0);
    return references;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept TableToSave$d1 = MetaAdapterFactory.getConcept(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5721437afL, "ltsdsl.structure.TableToSave");
    /*package*/ static final SConcept Table$$W = MetaAdapterFactory.getConcept(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5720c3a0cL, "ltsdsl.structure.Table");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink table$LR94 = MetaAdapterFactory.getReferenceLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5721437afL, 0x3fa6e5f5721437b0L, "table");
  }
}
