"""
lts_runtime.py
--------------
Python faithful port of LTSRuntime.java generated by LTSGenerator.xtend.

This exercises every primitive used by the three scenario generators:
  load, save, sort, filter, remove_duplicates, drop_columns,
  add_computed_column, update_column, append_rows, join, group, lookup,
  split, extract.

A Table is a dict with:
  columns : list[str]          – ordered column names
  rows    : list[dict]         – each row is {colName: value}
"""

from __future__ import annotations
import csv, os, re
from typing import Callable, Any


# ── AggFunction ────────────────────────────────────────────────────────────────

class AggFunction:
    SUM   = "SUM"
    AVG   = "AVG"
    MIN   = "MIN"
    MAX   = "MAX"
    COUNT = "COUNT"


# ── Table ──────────────────────────────────────────────────────────────────────

class Table:
    def __init__(self, columns: list[str], rows: list[dict] | None = None):
        self.columns: list[str]  = list(columns)
        self.rows:    list[dict] = [dict(r) for r in rows] if rows else []

    def row_count(self) -> int:
        return len(self.rows)

    def __repr__(self):
        return f"Table(cols={self.columns}, rows={self.rows})"


# ── CsvConfig ──────────────────────────────────────────────────────────────────

class CsvConfig:
    def __init__(self, path: str, delimiter: str = ",", has_header: bool = True):
        self.path       = path
        self.delimiter  = delimiter
        self.has_header = has_header


# ── LogCollector ───────────────────────────────────────────────────────────────

class LogCollector:
    def __init__(self, path: str | None = None):
        self.path    = path
        self.entries: list[str] = []

    def info   (self, msg): self.entries.append(f"[INFO]    {msg}")
    def warning(self, msg): self.entries.append(f"[WARNING] {msg}")
    def error  (self, msg): self.entries.append(f"[ERROR]   {msg}")

    def flush(self):
        for e in self.entries:
            print(e)
        if self.path:
            os.makedirs(os.path.dirname(self.path), exist_ok=True)
            with open(self.path, "a") as f:
                for e in self.entries:
                    f.write(e + "\n")
        self.entries.clear()


# ── CsvLoader ─────────────────────────────────────────────────────────────────

def load(cfg: CsvConfig) -> Table:
    cols: list[str]  = []
    rows: list[dict] = []
    with open(cfg.path, newline="") as f:
        reader = csv.reader(f, delimiter=cfg.delimiter)
        first  = True
        for parts in reader:
            if first and cfg.has_header:
                cols  = [p.strip() for p in parts]
                first = False
            else:
                if first:                                  # no header
                    cols  = [f"col{i}" for i in range(len(parts))]
                    first = False
                row = {cols[i]: _coerce(parts[i].strip()) for i in range(len(cols))}
                rows.append(row)
    return Table(cols, rows)

def _coerce(v: str) -> Any:
    """Try int → float → str."""
    try:    return int(v)
    except: pass
    try:    return float(v)
    except: pass
    return v


# ── CsvSaver ──────────────────────────────────────────────────────────────────

def save(table: Table, cfg: CsvConfig):
    os.makedirs(os.path.dirname(cfg.path), exist_ok=True)
    with open(cfg.path, "w", newline="") as f:
        writer = csv.writer(f, delimiter=cfg.delimiter)
        if cfg.has_header:
            writer.writerow(table.columns)
        for row in table.rows:
            writer.writerow([row.get(c, "") for c in table.columns])


# ── Transformation primitives ─────────────────────────────────────────────────

def sort_table(t: Table, cols: list[str], orders: list[str]) -> Table:
    def key_fn(row):
        return tuple(
            (_to_comparable(row.get(c)), )
            for c, o in zip(cols, orders)
        )
    # Multi-key sort with per-key direction
    import functools
    def cmp(a, b):
        for c, o in zip(cols, orders):
            va, vb = _to_comparable(a.get(c)), _to_comparable(b.get(c))
            if va < vb:  return -1 if o != "DESC" else  1
            if va > vb:  return  1 if o != "DESC" else -1
        return 0
    sorted_rows = sorted(t.rows, key=functools.cmp_to_key(cmp))
    return Table(t.columns, sorted_rows)


def filter_table(t: Table, predicate: Callable[[dict], bool]) -> Table:
    return Table(t.columns, [r for r in t.rows if predicate(r)])


def remove_duplicates(t: Table, keys: list[str]) -> Table:
    seen = set()
    kept = []
    for row in t.rows:
        k = tuple(str(row.get(c)) for c in keys)
        if k not in seen:
            seen.add(k)
            kept.append(row)
    return Table(t.columns, kept)


def drop_columns(t: Table, cols: list[str]) -> Table:
    remaining = [c for c in t.columns if c not in cols]
    rows = [{c: r[c] for c in remaining if c in r} for r in t.rows]
    return Table(remaining, rows)


def add_computed_column(t: Table, col_name: str,
                         fn: Callable[[dict], Any]) -> Table:
    new_cols = list(t.columns)
    if col_name not in new_cols:
        new_cols.append(col_name)
    rows = []
    for row in t.rows:
        r = dict(row)
        r[col_name] = fn(r)
        rows.append(r)
    return Table(new_cols, rows)


def update_column(t: Table, col_name: str,
                  fn: Callable[[dict], Any]) -> Table:
    return add_computed_column(t, col_name, fn)


def append_rows(dst: Table, src: Table) -> Table:
    """
    Bug found during testing (v1): if dst is None (e.g. an unloaded empty
    table), we must initialise it first.  Fixed here.
    """
    if dst is None:
        return Table(src.columns, list(src.rows))
    rows = list(dst.rows) + list(src.rows)
    # Union of columns, dst order first
    cols = list(dst.columns)
    for c in src.columns:
        if c not in cols:
            cols.append(c)
    return Table(cols, rows)


def join(left: Table, left_key: str,
         right: Table, right_key: str,
         agg_col: str | None = None,
         agg_fn:  str | None = None) -> Table:
    """
    Left-join left with right.
    If agg_col/agg_fn given, aggregate right by right_key first.
    """
    right_to_join = (group(right, [right_key], agg_col, agg_fn)
                     if agg_col and agg_fn else right)

    # Build lookup from right (last-write-wins for duplicates after group)
    lookup_map: dict[Any, dict] = {}
    for row in right_to_join.rows:
        lookup_map[row.get(right_key)] = row

    # Merged column list
    new_cols = list(left.columns)
    for c in right_to_join.columns:
        if c != right_key and c not in new_cols:
            new_cols.append(c)

    rows = []
    for left_row in left.rows:
        r = dict(left_row)
        right_row = lookup_map.get(left_row.get(left_key))
        if right_row:
            for k, v in right_row.items():
                if k != right_key:
                    r[k] = v
        rows.append(r)
    return Table(new_cols, rows)


def group(t: Table, keys: list[str], agg_col: str, agg_fn: str) -> Table:
    groups: dict[tuple, list[dict]] = {}
    for row in t.rows:
        k = tuple(row.get(c) for c in keys)
        groups.setdefault(k, []).append(row)

    result_rows = []
    for k_vals, g_rows in groups.items():
        r: dict = {keys[i]: k_vals[i] for i in range(len(keys))}
        r[agg_col] = _aggregate(g_rows, agg_col, agg_fn)
        result_rows.append(r)

    cols = list(keys) + ([agg_col] if agg_col not in keys else [])
    return Table(cols, result_rows)


def lookup(target: Table, target_key: str,
           ref: Table,    ref_key: str,
           fetch_col: str) -> Table:
    """VLOOKUP: bring fetch_col from ref into target by matching keys."""
    ref_map = {row.get(ref_key): row.get(fetch_col) for row in ref.rows}
    new_cols = list(target.columns)
    if fetch_col not in new_cols:
        new_cols.append(fetch_col)
    rows = []
    for row in target.rows:
        r = dict(row)
        r[fetch_col] = ref_map.get(row.get(target_key))
        rows.append(r)
    return Table(new_cols, rows)


def split_col(t: Table, src: str,
              delimiter: str | None, position: int | None,
              targets: list[str]) -> Table:
    new_cols = list(t.columns)
    for c in targets:
        if c not in new_cols:
            new_cols.append(c)
    rows = []
    for row in t.rows:
        r = dict(row)
        val = str(row.get(src, ""))
        if delimiter is not None:
            parts = val.split(delimiter, len(targets) - 1)
        else:
            p = position or 0
            parts = [val[:p], val[p:]]
        for i, tgt in enumerate(targets):
            r[tgt] = parts[i] if i < len(parts) else ""
        rows.append(r)
    return Table(new_cols, rows)


def extract_col(t: Table, src: str,
                pattern: str | None, start: int | None, end: int | None,
                target: str) -> Table:
    new_cols = list(t.columns)
    if target not in new_cols:
        new_cols.append(target)
    rows = []
    for row in t.rows:
        r = dict(row)
        val = str(row.get(src, ""))
        if pattern:
            m = re.search(pattern, val)
            r[target] = m.group() if m else ""
        else:
            r[target] = val[start:end]
        rows.append(r)
    return Table(new_cols, rows)


# ── Expression helpers ─────────────────────────────────────────────────────────

def col(row: dict, name: str) -> Any:
    return row.get(name)

def to_bool(v: Any) -> bool:
    if isinstance(v, bool): return v
    if isinstance(v, str):  return v.lower() == "true"
    return v is not None

def compare(left: Any, op: str, right: Any) -> bool:
    try:
        l, r = float(left), float(right)
        return {"==": l==r, "!=": l!=r, "<": l<r, "<=": l<=r,
                ">": l>r, ">=": l>=r}[op]
    except (TypeError, ValueError):
        ls, rs = str(left), str(right)
        return {"==": ls==rs, "!=": ls!=rs}.get(op, False)

def arithmetic(left: Any, op: str, right: Any) -> Any:
    # Bug fix v2: treat None as 0.0 so employees with no hours get payment=0.0
    # rather than None, which would silently corrupt downstream calculations.
    if left  is None: left  = 0
    if right is None: right = 0
    try:
        l, r = float(left), float(right)
        if op == "+": return l + r
        if op == "-": return l - r
        if op == "*": return l * r
        if op == "/": return l / r if r != 0 else None
    except (TypeError, ValueError):
        if op == "+": return str(left) + str(right)
    return None


# ── Internal helpers ──────────────────────────────────────────────────────────

def _to_comparable(v: Any):
    try:    return (0, float(v))
    except: return (1, str(v) if v is not None else "")

def _aggregate(rows: list[dict], col_name: str, fn: str) -> float:
    vals = [float(r[col_name]) for r in rows
            if r.get(col_name) is not None]
    if not vals: return 0.0
    if fn == AggFunction.SUM:   return sum(vals)
    if fn == AggFunction.AVG:   return sum(vals) / len(vals)
    if fn == AggFunction.MIN:   return min(vals)
    if fn == AggFunction.MAX:   return max(vals)
    if fn == AggFunction.COUNT: return float(len(vals))
    return 0.0
