/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.mydsl.lts.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.lts.Aggregation;
import org.xtext.example.mydsl.lts.JoinCondition;
import org.xtext.example.mydsl.lts.JoinStep;
import org.xtext.example.mydsl.lts.LtsPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Join Step</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.lts.impl.JoinStepImpl#getLeftTable <em>Left Table</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.lts.impl.JoinStepImpl#getRightTable <em>Right Table</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.lts.impl.JoinStepImpl#getJoinCondition <em>Join Condition</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.lts.impl.JoinStepImpl#getPreserveType <em>Preserve Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.lts.impl.JoinStepImpl#getAggregations <em>Aggregations</em>}</li>
 * </ul>
 *
 * @generated
 */
public class JoinStepImpl extends StepImpl implements JoinStep
{
  /**
   * The default value of the '{@link #getLeftTable() <em>Left Table</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeftTable()
   * @generated
   * @ordered
   */
  protected static final String LEFT_TABLE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLeftTable() <em>Left Table</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeftTable()
   * @generated
   * @ordered
   */
  protected String leftTable = LEFT_TABLE_EDEFAULT;

  /**
   * The default value of the '{@link #getRightTable() <em>Right Table</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRightTable()
   * @generated
   * @ordered
   */
  protected static final String RIGHT_TABLE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRightTable() <em>Right Table</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRightTable()
   * @generated
   * @ordered
   */
  protected String rightTable = RIGHT_TABLE_EDEFAULT;

  /**
   * The cached value of the '{@link #getJoinCondition() <em>Join Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJoinCondition()
   * @generated
   * @ordered
   */
  protected JoinCondition joinCondition;

  /**
   * The default value of the '{@link #getPreserveType() <em>Preserve Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPreserveType()
   * @generated
   * @ordered
   */
  protected static final String PRESERVE_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPreserveType() <em>Preserve Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPreserveType()
   * @generated
   * @ordered
   */
  protected String preserveType = PRESERVE_TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getAggregations() <em>Aggregations</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAggregations()
   * @generated
   * @ordered
   */
  protected EList<Aggregation> aggregations;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JoinStepImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LtsPackage.Literals.JOIN_STEP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLeftTable()
  {
    return leftTable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLeftTable(String newLeftTable)
  {
    String oldLeftTable = leftTable;
    leftTable = newLeftTable;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LtsPackage.JOIN_STEP__LEFT_TABLE, oldLeftTable, leftTable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRightTable()
  {
    return rightTable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRightTable(String newRightTable)
  {
    String oldRightTable = rightTable;
    rightTable = newRightTable;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LtsPackage.JOIN_STEP__RIGHT_TABLE, oldRightTable, rightTable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JoinCondition getJoinCondition()
  {
    return joinCondition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetJoinCondition(JoinCondition newJoinCondition, NotificationChain msgs)
  {
    JoinCondition oldJoinCondition = joinCondition;
    joinCondition = newJoinCondition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LtsPackage.JOIN_STEP__JOIN_CONDITION, oldJoinCondition, newJoinCondition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setJoinCondition(JoinCondition newJoinCondition)
  {
    if (newJoinCondition != joinCondition)
    {
      NotificationChain msgs = null;
      if (joinCondition != null)
        msgs = ((InternalEObject)joinCondition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LtsPackage.JOIN_STEP__JOIN_CONDITION, null, msgs);
      if (newJoinCondition != null)
        msgs = ((InternalEObject)newJoinCondition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LtsPackage.JOIN_STEP__JOIN_CONDITION, null, msgs);
      msgs = basicSetJoinCondition(newJoinCondition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LtsPackage.JOIN_STEP__JOIN_CONDITION, newJoinCondition, newJoinCondition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPreserveType()
  {
    return preserveType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPreserveType(String newPreserveType)
  {
    String oldPreserveType = preserveType;
    preserveType = newPreserveType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LtsPackage.JOIN_STEP__PRESERVE_TYPE, oldPreserveType, preserveType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Aggregation> getAggregations()
  {
    if (aggregations == null)
    {
      aggregations = new EObjectContainmentEList<Aggregation>(Aggregation.class, this, LtsPackage.JOIN_STEP__AGGREGATIONS);
    }
    return aggregations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LtsPackage.JOIN_STEP__JOIN_CONDITION:
        return basicSetJoinCondition(null, msgs);
      case LtsPackage.JOIN_STEP__AGGREGATIONS:
        return ((InternalEList<?>)getAggregations()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LtsPackage.JOIN_STEP__LEFT_TABLE:
        return getLeftTable();
      case LtsPackage.JOIN_STEP__RIGHT_TABLE:
        return getRightTable();
      case LtsPackage.JOIN_STEP__JOIN_CONDITION:
        return getJoinCondition();
      case LtsPackage.JOIN_STEP__PRESERVE_TYPE:
        return getPreserveType();
      case LtsPackage.JOIN_STEP__AGGREGATIONS:
        return getAggregations();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LtsPackage.JOIN_STEP__LEFT_TABLE:
        setLeftTable((String)newValue);
        return;
      case LtsPackage.JOIN_STEP__RIGHT_TABLE:
        setRightTable((String)newValue);
        return;
      case LtsPackage.JOIN_STEP__JOIN_CONDITION:
        setJoinCondition((JoinCondition)newValue);
        return;
      case LtsPackage.JOIN_STEP__PRESERVE_TYPE:
        setPreserveType((String)newValue);
        return;
      case LtsPackage.JOIN_STEP__AGGREGATIONS:
        getAggregations().clear();
        getAggregations().addAll((Collection<? extends Aggregation>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LtsPackage.JOIN_STEP__LEFT_TABLE:
        setLeftTable(LEFT_TABLE_EDEFAULT);
        return;
      case LtsPackage.JOIN_STEP__RIGHT_TABLE:
        setRightTable(RIGHT_TABLE_EDEFAULT);
        return;
      case LtsPackage.JOIN_STEP__JOIN_CONDITION:
        setJoinCondition((JoinCondition)null);
        return;
      case LtsPackage.JOIN_STEP__PRESERVE_TYPE:
        setPreserveType(PRESERVE_TYPE_EDEFAULT);
        return;
      case LtsPackage.JOIN_STEP__AGGREGATIONS:
        getAggregations().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LtsPackage.JOIN_STEP__LEFT_TABLE:
        return LEFT_TABLE_EDEFAULT == null ? leftTable != null : !LEFT_TABLE_EDEFAULT.equals(leftTable);
      case LtsPackage.JOIN_STEP__RIGHT_TABLE:
        return RIGHT_TABLE_EDEFAULT == null ? rightTable != null : !RIGHT_TABLE_EDEFAULT.equals(rightTable);
      case LtsPackage.JOIN_STEP__JOIN_CONDITION:
        return joinCondition != null;
      case LtsPackage.JOIN_STEP__PRESERVE_TYPE:
        return PRESERVE_TYPE_EDEFAULT == null ? preserveType != null : !PRESERVE_TYPE_EDEFAULT.equals(preserveType);
      case LtsPackage.JOIN_STEP__AGGREGATIONS:
        return aggregations != null && !aggregations.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (leftTable: ");
    result.append(leftTable);
    result.append(", rightTable: ");
    result.append(rightTable);
    result.append(", preserveType: ");
    result.append(preserveType);
    result.append(')');
    return result.toString();
  }

} //JoinStepImpl
