/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.validation;

import org.eclipse.xtext.validation.Check;
import excelltsmetamodel.AppendRows;
import excelltsmetamodel.Association;
import excelltsmetamodel.ExcelltsmetamodelPackage;

import org.xtext.example.mydsl.validation.MyDslValidatorAssociation;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class MyDslValidatorAssociation extends AbstractMyDslValidator {
	
	public static final String ASSOCIATION_ORIGIN_COL_AND_DESTIN_COL_TYPES_MUST_BE_THE_SAME = "Origin column and destin column types of association step must be the same.";
	public static final String ASSOCIATION_STEP_COLUMNS_MUST_BE_IN_THE_TABLES = "Association step columns must be in the tables.";
	
	/**
	 * Method to verify if the originCol and destinCol types of the association step are the same.
	 * 
	 * @param appendRowsStep The append rows step to verify.
	 */
	@Check
	public void originColAndDestinColTypesMustBeTheSame(AppendRows appendRowsStep) {
	    for(Association association : appendRowsStep.getAssociations()) {
	    	if(association.getOriginCol().getDataType() != association.getDestinCol().getDataType()) {
				error(ASSOCIATION_ORIGIN_COL_AND_DESTIN_COL_TYPES_MUST_BE_THE_SAME, ExcelltsmetamodelPackage.Literals.APPEND_ROWS__ASSOCIATIONS, ASSOCIATION_ORIGIN_COL_AND_DESTIN_COL_TYPES_MUST_BE_THE_SAME);
	    	}
	    }
	}
	
	/**
	 * Method to verify if the association step columns are in the tables.
	 * 
	 * @param appendRowsStep The append rows step to verify.
	 */
	@Check
	public void associationStepColumnsAreInTheTables(AppendRows appendRowsStep) {
		for(Association association : appendRowsStep.getAssociations()) {
			if(!appendRowsStep.getOriginTable().getColumns().contains(association.getOriginCol())
					|| !appendRowsStep.getDestinTable().getColumns().contains(association.getDestinCol())) {
				error(ASSOCIATION_STEP_COLUMNS_MUST_BE_IN_THE_TABLES, ExcelltsmetamodelPackage.Literals.APPEND_ROWS__ASSOCIATIONS, ASSOCIATION_STEP_COLUMNS_MUST_BE_IN_THE_TABLES);
			}
		}
	}
}
