/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.validation;

import org.eclipse.xtext.validation.Check;
import excelltsmetamodel.ExcelltsmetamodelPackage;
import excelltsmetamodel.TableToImport;

import org.xtext.example.mydsl.validation.MyDslValidatorTableToImport;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class MyDslValidatorTableToImport extends AbstractMyDslValidator {

	public static final String PATH_OF_TABLE_TO_IMPORT_MUST_NOT_BE_BLANK = "The path of a table to import must not be blank.";
	public static final String DELIMITER_OF_TABLE_TO_IMPORT_MUST_NOT_BE_EMPTY = "The delimiter of a table to import must not be empty.";
	
	/**
	 * Method to verify if a path of a table to import is not blank.
	 * 
	 * @param tableToImport The table to import to verify.
	 */
	@Check
	public void pathOfTableToImportMustNotBeBlank(TableToImport tableToImport) {
	    if(tableToImport.getPath().isBlank()||tableToImport.getPath().isEmpty()) {
	    	error(PATH_OF_TABLE_TO_IMPORT_MUST_NOT_BE_BLANK, ExcelltsmetamodelPackage.Literals.TABLE_TO_IMPORT__PATH, PATH_OF_TABLE_TO_IMPORT_MUST_NOT_BE_BLANK);
	    }
	}
	
	/**
	 * Method to verify if a delimiter of a table to import is not empty.
	 * 
	 * @param tableToImport The table to import to verify.
	 */
	@Check
	public void delimiterOfTableToImportMustNotBeEmpty(TableToImport tableToImport) {
	    if(tableToImport.getDelimiter().isEmpty()) {
	    	error(DELIMITER_OF_TABLE_TO_IMPORT_MUST_NOT_BE_EMPTY, ExcelltsmetamodelPackage.Literals.TABLE_TO_IMPORT__DELIMITER, DELIMITER_OF_TABLE_TO_IMPORT_MUST_NOT_BE_EMPTY);
	    }
	}
}
