/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.validation;

import org.eclipse.xtext.validation.Check;
import excelltsmetamodel.DataType;
import excelltsmetamodel.ExcelltsmetamodelPackage;
import excelltsmetamodel.Lookup;
import excelltsmetamodel.LookupOperationType;

import org.xtext.example.mydsl.validation.MyDslValidatorLookup;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class MyDslValidatorLookup extends AbstractMyDslValidator {

	public static final String LOOKUP_STEP_COLUMN_MUST_BELONG_TO_THE_TABLE = "Lookup step column must belong to the table.";
	public static final String LOOKUP_STEP_OPERAND_COLUMN_MUST_BELONG_TO_THE_TABLE = "Lookup step operand column must belong to the table.";
	public static final String LOOKUP_STEP_COLUMN_AND_OPERAND_COLUMN_MUST_BE_DIFFERENT = "Lookup step column and operand column must be different.";
	public static final String LOOKUP_STEP_MATCH_COLUMN_MUST_BELONG_TO_THE_LOOKUP_TABLE = "Lookup step match column must belong to the lookup table.";
	public static final String LOOKUP_STEP_LOOKUP_COLUMN_MUST_BELONG_TO_THE_LOOKUP_TABLE = "Lookup step lookup column must belong to the lookup table.";
	public static final String LOOKUP_STEP_MATCH_COLUMN_AND_LOOKUP_COLUMN_MUST_BE_DIFFERENT = "Lookup step match column and lookup column must be different.";
	public static final String LOOKUP_STEP_OPERAND_LOOKUP_AND_RESULT_COLUMNS_TYPES_MUST_BE_THE_SAME = "Lookup step operand, lookup and result columns types must be the same.";
	public static final String LOOKUP_STEP_COLUMN_AND_MATCH_COLUMN_TYPES_MUST_BE_THE_SAME = "Lookup step column and match column types must be the same.";
	public static final String LOOKUP_STEP_DOES_NOT_SUPPORT_DATE_DATA_TYPE = "Lookup step does not support date data type.";
	public static final String LOOKUP_STEP_OPERAND_AND_LOOKUP_COLUMNS_MUST_MATCH_OPERATION = "Lookup step operand and lookup columns must match operation type.";
	public static final String LOOKUP_STEP_RESULT_TABLE_MUST_HAVE_ALL_TABLE_COLUMNS = "Lookup step result table must have all the table columns in order.";
	public static final String LOOKUP_STEP_RESULT_TABLE_MUST_HAVE_THE_RESULT_COLUMN = "Lookup step result table must have the result column as last.";
	public static final String LOOKUP_STEP_TO_SAME_TABLE_IS_IMPOSSIBLE_COLUMN_AND_MATCH_COLUMN_MUST_BE_THE_SAME = "Lookup step to the same table is impossible: column and match column must be the same.";
	public static final String LOOKUP_STEP_TO_SAME_TABLE_IS_IMPOSSIBLE_OPERNAD_COLUMN_AND_LOOKUP_COLUMN_MUST_BE_DIFFERENT = "Lookup step to the same table is impossible: operand column and lookup column must be different.";
	public static final String LOOKUP_STEP_TO_SAME_TABLE_IS_IMPOSSIBLE_RESULT_COLUMN_MUST_BE_DIFFERENT_THAN_ALL_OTHER_COLUMNS = "Lookup step to the same table is impossible: result column must be different than all the others.";
	public static final String LOOKUP_STEP_IF_TABLES_DIFFERENT_RESULT_TABLE_MUST_BE_DIFFERENT_THAN_LOOKUP_TABLE = "Lookup step tables are different, so result table must be different than lookup table.";

	/**
	 * Method to verify if the lookup step column and operand column belong to the table and are different.
	 * 
	 * @param lookupStep The lookup step to verify.
	 */
	@Check
	public void columnAndOperandColumnBelongToTableAndAreDifferent(Lookup lookupStep) {
	    if (!lookupStep.getTable().getColumns().contains(lookupStep.getColumn())) {
	    	error(LOOKUP_STEP_COLUMN_MUST_BELONG_TO_THE_TABLE, ExcelltsmetamodelPackage.Literals.LOOKUP__LOOKUP_COLUMN, LOOKUP_STEP_COLUMN_MUST_BELONG_TO_THE_TABLE);
	    } 
	    if (!lookupStep.getTable().getColumns().contains(lookupStep.getOperandColumn())) {
	    	error(LOOKUP_STEP_OPERAND_COLUMN_MUST_BELONG_TO_THE_TABLE, ExcelltsmetamodelPackage.Literals.LOOKUP__OPERAND_COLUMN, LOOKUP_STEP_OPERAND_COLUMN_MUST_BELONG_TO_THE_TABLE);
	    } 
	    if(lookupStep.getColumn().equals(lookupStep.getOperandColumn())) {
	    	error(LOOKUP_STEP_COLUMN_AND_OPERAND_COLUMN_MUST_BE_DIFFERENT, ExcelltsmetamodelPackage.Literals.LOOKUP__OPERAND_COLUMN, LOOKUP_STEP_COLUMN_AND_OPERAND_COLUMN_MUST_BE_DIFFERENT);
	    }
	}
	
	/**
	 * Method to verify if the lookup step match column and lookup column belong to the lookup table and are different.
	 * 
	 * @param lookupStep The lookup step to verify.
	 */
	@Check
	public void matchColumnAndLookupColumnBelongToLookupTableAndAreDifferent(Lookup lookupStep) {
	    if (!lookupStep.getLookupTable().getColumns().contains(lookupStep.getMatchColumn())) {
	    	error(LOOKUP_STEP_MATCH_COLUMN_MUST_BELONG_TO_THE_LOOKUP_TABLE, ExcelltsmetamodelPackage.Literals.LOOKUP__MATCH_COLUMN, LOOKUP_STEP_MATCH_COLUMN_MUST_BELONG_TO_THE_LOOKUP_TABLE);
	    } 
	    if (!lookupStep.getLookupTable().getColumns().contains(lookupStep.getLookupColumn())) {
	    	error(LOOKUP_STEP_LOOKUP_COLUMN_MUST_BELONG_TO_THE_LOOKUP_TABLE, ExcelltsmetamodelPackage.Literals.LOOKUP__LOOKUP_COLUMN, LOOKUP_STEP_LOOKUP_COLUMN_MUST_BELONG_TO_THE_LOOKUP_TABLE);
	    } 
	    if(lookupStep.getMatchColumn().equals(lookupStep.getLookupColumn())) {
	    	error(LOOKUP_STEP_MATCH_COLUMN_AND_LOOKUP_COLUMN_MUST_BE_DIFFERENT, ExcelltsmetamodelPackage.Literals.LOOKUP__LOOKUP_COLUMN, LOOKUP_STEP_MATCH_COLUMN_AND_LOOKUP_COLUMN_MUST_BE_DIFFERENT);
	    }
	}
	
	/**
	 * Method to verify if operand column, lookup column and the result column types are the same.
	 * 
	 * @param lookupStep The lookup step to verify.
	 */
	@Check
	public void lookupStepOperandLookupAndResultTypesMustBeTheSame(Lookup lookupStep) {
	    if(!lookupStep.getOperandColumn().getDataType().equals(lookupStep.getLookupColumn().getDataType()) ||
	    		!lookupStep.getOperandColumn().getDataType().equals(lookupStep.getResultColumn().getDataType()) ||
	    		!lookupStep.getResultColumn().getDataType().equals(lookupStep.getLookupColumn().getDataType())) {
	    	error(LOOKUP_STEP_OPERAND_LOOKUP_AND_RESULT_COLUMNS_TYPES_MUST_BE_THE_SAME, ExcelltsmetamodelPackage.Literals.LOOKUP__OPERAND_COLUMN, LOOKUP_STEP_OPERAND_LOOKUP_AND_RESULT_COLUMNS_TYPES_MUST_BE_THE_SAME);
	    }
	}
	
	/**
	 * Method to verify if column and match column types are the same.
	 * 
	 * @param lookupStep The lookup step to verify.
	 */
	@Check
	public void columnAndMatchColumnTypesMustBeTheSame(Lookup lookupStep) {
	    if(!lookupStep.getColumn().getDataType().equals(lookupStep.getMatchColumn().getDataType())) {
	    	error(LOOKUP_STEP_COLUMN_AND_MATCH_COLUMN_TYPES_MUST_BE_THE_SAME, ExcelltsmetamodelPackage.Literals.LOOKUP__MATCH_COLUMN, LOOKUP_STEP_COLUMN_AND_MATCH_COLUMN_TYPES_MUST_BE_THE_SAME);
	    }
	}
	
	/**
	 * Method to verify if operand column and lookup column match operation type.
	 * 
	 * @param lookupStep The lookup step to verify.
	 */
	@Check
	public void operandAndLookupColumnsTypesMustSupportTheOperationType(Lookup lookupStep) {
	    if(lookupStep.getOperandColumn().getDataType().equals(DataType.DATE)) {
	    	error(LOOKUP_STEP_DOES_NOT_SUPPORT_DATE_DATA_TYPE, ExcelltsmetamodelPackage.Literals.LOOKUP__OPERAND_COLUMN, LOOKUP_STEP_DOES_NOT_SUPPORT_DATE_DATA_TYPE);
	    }
	    if((lookupStep.getOperandColumn().getDataType().equals(DataType.NUMBER) && lookupStep.getOperation().equals(LookupOperationType.TEXT_CONCAT)) ||
	    		(lookupStep.getOperandColumn().getDataType().equals(DataType.TEXT) && !lookupStep.getOperation().equals(LookupOperationType.TEXT_CONCAT))){
	    	error(LOOKUP_STEP_OPERAND_AND_LOOKUP_COLUMNS_MUST_MATCH_OPERATION, ExcelltsmetamodelPackage.Literals.LOOKUP__OPERAND_COLUMN, LOOKUP_STEP_OPERAND_AND_LOOKUP_COLUMNS_MUST_MATCH_OPERATION);
	    }
	}
	
	/**
	 * Method to verify if result table has all the table columns plus the result column.
	 * 
	 * @param lookupStep The lookup step to verify.
	 */
	@Check
	public void resultTableMustHaveAllTableColumnsAndTheResultColumn(Lookup lookupStep) {
		for(int i = 0; i < lookupStep.getTable().getColumns().size(); i++) {
			if(!lookupStep.getResultTable().getColumns().get(i).getName().equals(lookupStep.getTable().getColumns().get(i).getName()) ||
					!lookupStep.getResultTable().getColumns().get(i).getDataType().equals(lookupStep.getTable().getColumns().get(i).getDataType())) {
				error(LOOKUP_STEP_RESULT_TABLE_MUST_HAVE_ALL_TABLE_COLUMNS, ExcelltsmetamodelPackage.Literals.LOOKUP__RESULT_TABLE, LOOKUP_STEP_RESULT_TABLE_MUST_HAVE_ALL_TABLE_COLUMNS);
			}
		}
		if(!lookupStep.getResultTable().getColumns().get(lookupStep.getResultTable().getColumns().size() - 1).getName().equals(lookupStep.getResultColumn().getName()) ||
				!lookupStep.getResultTable().getColumns().get(lookupStep.getResultTable().getColumns().size() - 1).getDataType().equals(lookupStep.getResultColumn().getDataType())) {
	    	error(LOOKUP_STEP_RESULT_TABLE_MUST_HAVE_THE_RESULT_COLUMN, ExcelltsmetamodelPackage.Literals.LOOKUP__RESULT_TABLE, LOOKUP_STEP_RESULT_TABLE_MUST_HAVE_THE_RESULT_COLUMN);
		}
	}
	
	/**
	 * Method to verify if lookup to the same table is possible.
	 * 
	 * @param lookupStep The lookup step to verify.
	 */
	@Check
	public void lookupToTheSameTableMustBePossible(Lookup lookupStep) {
		if(lookupStep.getTable().equals(lookupStep.getLookupTable()) && !lookupStep.getColumn().equals(lookupStep.getMatchColumn())) {
	    	error(LOOKUP_STEP_TO_SAME_TABLE_IS_IMPOSSIBLE_COLUMN_AND_MATCH_COLUMN_MUST_BE_THE_SAME, ExcelltsmetamodelPackage.Literals.LOOKUP__MATCH_COLUMN, LOOKUP_STEP_TO_SAME_TABLE_IS_IMPOSSIBLE_COLUMN_AND_MATCH_COLUMN_MUST_BE_THE_SAME);
		}
		if(lookupStep.getTable().equals(lookupStep.getLookupTable()) && lookupStep.getOperandColumn().equals(lookupStep.getLookupColumn())) {
	    	error(LOOKUP_STEP_TO_SAME_TABLE_IS_IMPOSSIBLE_OPERNAD_COLUMN_AND_LOOKUP_COLUMN_MUST_BE_DIFFERENT, ExcelltsmetamodelPackage.Literals.LOOKUP__LOOKUP_COLUMN, LOOKUP_STEP_TO_SAME_TABLE_IS_IMPOSSIBLE_OPERNAD_COLUMN_AND_LOOKUP_COLUMN_MUST_BE_DIFFERENT);
		}
		if((lookupStep.getTable().equals(lookupStep.getLookupTable())) && (
				lookupStep.getResultColumn().equals(lookupStep.getColumn()) ||
				lookupStep.getResultColumn().equals(lookupStep.getMatchColumn()) || 
				lookupStep.getResultColumn().equals(lookupStep.getOperandColumn()) ||
				lookupStep.getResultColumn().equals(lookupStep.getLookupColumn())
				)) {
	    	error(LOOKUP_STEP_TO_SAME_TABLE_IS_IMPOSSIBLE_RESULT_COLUMN_MUST_BE_DIFFERENT_THAN_ALL_OTHER_COLUMNS, ExcelltsmetamodelPackage.Literals.LOOKUP__RESULT_COLUMN, LOOKUP_STEP_TO_SAME_TABLE_IS_IMPOSSIBLE_RESULT_COLUMN_MUST_BE_DIFFERENT_THAN_ALL_OTHER_COLUMNS);
		}
	}
	
	/**
	 * Method to verify if table and lookup table are different than result table and lookup table must be different.
	 * 
	 * @param lookupStep The lookup step to verify.
	 */
	@Check
	public void ifTablesDifferentResultTableAndLookupTableMustBeDifferent(Lookup lookupStep) {
		if(!lookupStep.getTable().equals(lookupStep.getLookupTable()) && lookupStep.getResultTable().equals(lookupStep.getLookupTable())) {
	    	error(LOOKUP_STEP_IF_TABLES_DIFFERENT_RESULT_TABLE_MUST_BE_DIFFERENT_THAN_LOOKUP_TABLE, ExcelltsmetamodelPackage.Literals.LOOKUP__RESULT_TABLE, LOOKUP_STEP_IF_TABLES_DIFFERENT_RESULT_TABLE_MUST_BE_DIFFERENT_THAN_LOOKUP_TABLE);
		}
	}
}
