/* Generated by Xtext. */
package org.example.lts.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLtsScopeProvider extends DelegatingScopeProvider {
}
