package program.src.main.java.org.enorm.domain.steps.groupByStep;

/*Generated by MPS */


public class FactoryGroupByStep {
  private static IGroupByStep step;

  public static void setStep(IGroupByStep s) {
    step = s;
  }

  public static IGroupByStep getStep() {
    return step;
  }
}
