#

pluginName = excelltsmetamodel Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Model_type = Model
_UI_Step_type = Step
_UI_FlowStep_type = Flow Step
_UI_FinalStep_type = Final Step
_UI_Save_type = Save
_UI_Table_type = Table
_UI_Group_type = Group
_UI_Column_type = Column
_UI_Sort_type = Sort
_UI_AppendRows_type = Append Rows
_UI_TableToSave_type = Table To Save
_UI_Association_type = Association
_UI_Filter_type = Filter
_UI_GenericStep_type = Generic Step
_UI_Join_type = Join
_UI_Import_type = Import
_UI_TableToImport_type = Table To Import
_UI_Lookup_type = Lookup
_UI_RemoveDuplicates_type = Remove Duplicates
_UI_Concat_type = Concat
_UI_StringManipulation_type = String Manipulation
_UI_Split_type = Split
_UI_Extract_type = Extract
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Model_name_feature = Name
_UI_Model_logs_feature = Logs
_UI_Model_tables_feature = Tables
_UI_Model_steps_feature = Steps
_UI_Step_name_feature = Name
_UI_Step_description_feature = Description
_UI_FlowStep_next_feature = Next
_UI_Save_tablesToSave_feature = Tables To Save
_UI_Table_name_feature = Name
_UI_Table_columns_feature = Columns
_UI_Group_table_feature = Table
_UI_Group_groupBy_feature = Group By
_UI_Group_resultTable_feature = Result Table
_UI_Group_operandColumn_feature = Operand Column
_UI_Group_operation_feature = Operation
_UI_Group_resultColumn_feature = Result Column
_UI_Column_name_feature = Name
_UI_Column_dataType_feature = Data Type
_UI_Sort_table_feature = Table
_UI_Sort_column_feature = Column
_UI_Sort_order_feature = Order
_UI_AppendRows_originTable_feature = Origin Table
_UI_AppendRows_destinTable_feature = Destin Table
_UI_AppendRows_associations_feature = Associations
_UI_TableToSave_table_feature = Table
_UI_TableToSave_path_feature = Path
_UI_TableToSave_columnsNames_feature = Columns Names
_UI_Association_originCol_feature = Origin Col
_UI_Association_destinCol_feature = Destin Col
_UI_Filter_table_feature = Table
_UI_Filter_column_feature = Column
_UI_Filter_operand_feature = Operand
_UI_Filter_operator_feature = Operator
_UI_Join_tableLeft_feature = Table Left
_UI_Join_tableRight_feature = Table Right
_UI_Join_columnLeft_feature = Column Left
_UI_Join_columnRight_feature = Column Right
_UI_Join_type_feature = Type
_UI_Join_resultTable_feature = Result Table
_UI_Join_selectColumns_feature = Select Columns
_UI_Import_tablesToImport_feature = Tables To Import
_UI_TableToImport_table_feature = Table
_UI_TableToImport_path_feature = Path
_UI_TableToImport_delimiter_feature = Delimiter
_UI_TableToImport_deleteMismatchedTypes_feature = Delete Mismatched Types
_UI_Lookup_table_feature = Table
_UI_Lookup_lookupTable_feature = Lookup Table
_UI_Lookup_column_feature = Column
_UI_Lookup_operandColumn_feature = Operand Column
_UI_Lookup_matchColumn_feature = Match Column
_UI_Lookup_lookupColumn_feature = Lookup Column
_UI_Lookup_resultColumn_feature = Result Column
_UI_Lookup_operation_feature = Operation
_UI_Lookup_resultTable_feature = Result Table
_UI_RemoveDuplicates_table_feature = Table
_UI_RemoveDuplicates_column_feature = Column
_UI_Concat_sourceA_feature = Source A
_UI_Concat_sourceB_feature = Source B
_UI_Concat_resultColumn_feature = Result Column
_UI_Concat_resultTable_feature = Result Table
_UI_StringManipulation_table_feature = Table
_UI_Split_source_feature = Source
_UI_Split_resultColumnB_feature = Result Column B
_UI_Split_resultColumnA_feature = Result Column A
_UI_Split_delimiter_feature = Delimiter
_UI_Split_atCharIndex_feature = At Char Index
_UI_Split_resultTable_feature = Result Table
_UI_Extract_column_feature = Column
_UI_Extract_lbChar_feature = Lb Char
_UI_Extract_ubChar_feature = Ub Char
_UI_Extract_pattern_feature = Pattern
_UI_Unknown_feature = Unspecified

_UI_JoinType_INNER_literal = INNER
_UI_JoinType_OUTER_literal = OUTER
_UI_JoinType_LEFT_literal = LEFT
_UI_JoinType_RIGHT_literal = RIGHT
_UI_OrderType_ASC_literal = ASC
_UI_OrderType_DESC_literal = DESC
_UI_ColumnOperationType_INSERT_literal = INSERT
_UI_ColumnOperationType_REMOVE_literal = REMOVE
_UI_DataType_TEXT_literal = TEXT
_UI_DataType_NUMBER_literal = NUMBER
_UI_DataType_DATE_literal = DATE
_UI_LookupOperationType_NUMERIC_SUM_literal = NUMERIC_SUM
_UI_LookupOperationType_NUMERIC_SUBTRACT_literal = NUMERIC_SUBTRACT
_UI_LookupOperationType_NUMERIC_MULTIPLY_literal = NUMERIC_MULTIPLY
_UI_LookupOperationType_NUMERIC_DIVIDE_literal = NUMERIC_DIVIDE
_UI_LookupOperationType_TEXT_CONCAT_literal = TEXT_CONCAT
_UI_FilterOperatorType_EQUALS_literal = EQUALS
_UI_FilterOperatorType_LESS_THAN_literal = LESS_THAN
_UI_FilterOperatorType_GREATER_THAN_literal = GREATER_THAN
_UI_FilterOperatorType_LESS_OR_EQUALS_THAN_literal = LESS_OR_EQUALS_THAN
_UI_FilterOperatorType_GREATER_OR_EQUALS_THAN_literal = GREATER_OR_EQUALS_THAN
_UI_GroupOperationType_MAX_literal = MAX
_UI_GroupOperationType_MIN_literal = MIN
_UI_GroupOperationType_COUNT_literal = COUNT
_UI_GroupOperationType_SUM_literal = SUM
_UI_GroupOperationType_AVERAGE_literal = AVERAGE
