package program.src.main.java.org.enorm.domain.steps.appendRowsStep;

/*Generated by MPS */

import program.src.main.java.org.enorm.domain.tables.Table;
import java.util.Map;
import program.src.main.java.org.enorm.domain.tables.Column;

public interface IAppendRowsStep {
  void apply(Table from, Table to, Map<Column, Column> columnsMapping);
}
