/*
 * LTSGenerator.xtend
 *
 * Code generator for the LTS DSL.
 * Transforms a validated LTS model into runnable Java source files.
 *
 * Architecture of the generated code:
 *   <processName>/
 *       Main.java            ← entry point; orchestrates steps in order
 *       TableSchema.java     ← generated column enum for type-safe access
 *       LTSRuntime.java      ← always-present runtime copied from template
 *       CustomFunctions.java ← user-extension stub (never overwritten)
 *
 * The LTSRuntime.java (a fixed, non-generated file) provides:
 *   - Table class (List<Map<String,Object>> + schema)
 *   - CsvLoader / CsvSaver
 *   - LogCollector
 *   - All transformation primitives (sort, filter, join, group …)
 *
 * Package: org.lts.generator
 */
package org.lts.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import org.lts.lTS.*

class LTSGenerator extends AbstractGenerator {

    override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
        for (process : resource.allContents.toIterable.filter(Process)) {
            val pkg = process.name.toLowerCase

            // Always write the runtime support classes (idempotent – overwrite OK)
            fsa.generateFile(pkg + "/LTSRuntime.java",       generateRuntime(pkg))
            fsa.generateFile(pkg + "/TableSchema.java",      generateSchemaEnum(process, pkg))

            // Write CustomFunctions.java only if it does not exist yet
            // (Xtext IFileSystemAccess2 does not expose "exists", so we use a guard comment)
            fsa.generateFile(pkg + "/CustomFunctions.java",  generateCustomFunctionsStub(pkg))

            // Main orchestrator – always regenerated from the model
            fsa.generateFile(pkg + "/Main.java",             generateMain(process, pkg))
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Main.java  – orchestrates the steps in the order they appear in the model
    // ─────────────────────────────────────────────────────────────────────────
    def private String generateMain(Process process, String pkg) '''
        package «pkg»;

        import java.util.*;
        import java.io.*;

        /**
         * Generated by the LTS DSL generator.
         * Process : «process.name»
         * Description : «process.description ?: "(none)"»
         *
         * DO NOT EDIT – re-generate from the .lts model to update this file.
         * To add custom logic, edit CustomFunctions.java instead.
         */
        public class Main {

            public static void main(String[] args) throws Exception {
                LogCollector log = new LogCollector(
                    «IF process.log !== null»"«process.log.path»"«ELSE»null«ENDIF»
                );

                try {
                    run(log);
                } catch (Exception e) {
                    log.error("Unexpected error: " + e.getMessage());
                } finally {
                    log.flush();
                }
            }

            private static void run(LogCollector log) throws Exception {

                // ── Data source configurations ───────────────────────────────
                «FOR ds : process.sources»
                    «IF ds instanceof CsvDataSource»
                        CsvConfig «ds.name»Config = new CsvConfig(
                            "«(ds as CsvDataSource).path»",
                            «IF (ds as CsvDataSource).delimiter !== null»"«(ds as CsvDataSource).delimiter»"«ELSE»","«ENDIF»,
                            «(ds as CsvDataSource).hasHeader?.literal ?: "true"»
                        );
                    «ENDIF»
                «ENDFOR»

                // ── Table instances ──────────────────────────────────────────
                «FOR tbl : process.tables»
                    Table «tbl.name» = null;
                «ENDFOR»

                // ── Steps ────────────────────────────────────────────────────
                «FOR step : process.steps»
                    «generateStep(step, process)»
                «ENDFOR»
            }
        }
    '''

    // ─────────────────────────────────────────────────────────────────────────
    // Step dispatch
    // ─────────────────────────────────────────────────────────────────────────
    def private dispatch String generateStep(LoadStep step, Process process) '''
        // LOAD «step.table.name»
        «step.table.name» = CsvLoader.load(«datasourceConfigName(step.table, process)»Config);
        log.info("Loaded table '«step.table.name»' with " + «step.table.name».rowCount() + " rows.");
    '''

    def private dispatch String generateStep(SaveStep step, Process process) '''
        // SAVE «step.table.name»
        «IF step.table instanceof OutputTableDeclaration»
            CsvSaver.save(«step.table.name», «step.table.name»OutputConfig);
            log.info("Saved table '«step.table.name»'.");
        «ELSEIF step.table.name == process.log?.name»
            log.flush();
        «ELSE»
            // Save: table '«step.table.name»' – no output datasource configured; skipping.
            log.warning("Table '«step.table.name»' has no output datasource; not saved.");
        «ENDIF»
    '''

    def private dispatch String generateStep(SortStep step, Process process) '''
        // SORT «step.table.name» BY «step.sortKeys.map[k | k.column + " " + (k.order?.literal ?: "ASC")].join(", ")»
        «step.table.name» = LTSRuntime.sort(«step.table.name»,
            Arrays.asList(«step.sortKeys.map[k | '"' + k.column + '"'].join(", ")»),
            Arrays.asList(«step.sortKeys.map[k | '"' + (k.order?.literal ?: "ASC") + '"'].join(", ")»)
        );
    '''

    def private dispatch String generateStep(FilterStep step, Process process) '''
        // FILTER «step.table.name» WHERE «expressionToJava(step.condition)»
        «step.table.name» = LTSRuntime.filter(«step.table.name», row ->
            «expressionToJava(step.condition)»
        );
    '''

    def private dispatch String generateStep(RemoveDuplicatesStep step, Process process) '''
        // REMOVE DUPLICATES «step.table.name» BY «step.keys.join(", ")»
        «step.table.name» = LTSRuntime.removeDuplicates(«step.table.name»,
            Arrays.asList(«step.keys.map[k | '"' + k + '"'].join(", ")»)
        );
    '''

    def private dispatch String generateStep(RemoveColumnsStep step, Process process) '''
        // DROP COLUMNS «step.columns.join(", ")» FROM «step.table.name»
        «step.table.name» = LTSRuntime.dropColumns(«step.table.name»,
            Arrays.asList(«step.columns.map[c | '"' + c + '"'].join(", ")»)
        );
    '''

    def private dispatch String generateStep(InsertColumnStep step, Process process) '''
        // ADD COLUMN «step.name» : «step.type.literal» = «expressionToJava(step.expression)»  TO «step.table.name»
        «step.table.name» = LTSRuntime.addComputedColumn(«step.table.name», "«step.name»", row ->
            «expressionToJava(step.expression)»
        );
    '''

    def private dispatch String generateStep(CopyStep step, Process process) '''
        // COPY «step.source.name» INTO «step.target.name»
        «step.target.name» = LTSRuntime.appendRows(«step.target.name», «step.source.name»);
    '''

    def private dispatch String generateStep(JoinStep step, Process process) '''
        // JOIN «step.left.name» WITH «step.right.name» ON «step.leftKey» = «step.rightKey»«
            IF step.aggFunction !== null» AGGREGATING «step.aggColumn» USING «step.aggFunction.literal»«ENDIF»
        «step.left.name» = LTSRuntime.join(
            «step.left.name», "«step.leftKey»",
            «step.right.name», "«step.rightKey»"
            «IF step.aggFunction !== null»,
            "«step.aggColumn»", LTSRuntime.AggFunction.«step.aggFunction.literal»
            «ENDIF»
        );
    '''

    def private dispatch String generateStep(AppendStep step, Process process) '''
        // APPEND «step.source.name» TO «step.target.name»
        «step.target.name» = LTSRuntime.appendRows(«step.target.name», «step.source.name»);
    '''

    def private dispatch String generateStep(GroupStep step, Process process) '''
        // GROUP «step.table.name» BY «step.groupKeys.join(", ")» AGGREGATING «step.aggColumn» USING «step.aggFunction.literal» INTO «step.result.name»
        «step.result.name» = LTSRuntime.group(
            «step.table.name»,
            Arrays.asList(«step.groupKeys.map[k | '"' + k + '"'].join(", ")»),
            "«step.aggColumn»",
            LTSRuntime.AggFunction.«step.aggFunction.literal»
        );
    '''

    def private dispatch String generateStep(LookupStep step, Process process) '''
        // LOOKUP «step.fetchColumn» FROM «step.reference.name» ON «step.referenceKey» INTO «step.target.name» USING «step.targetKey»
        «step.target.name» = LTSRuntime.lookup(
            «step.target.name», "«step.targetKey»",
            «step.reference.name», "«step.referenceKey»",
            "«step.fetchColumn»"
        );
    '''

    def private dispatch String generateStep(ConcatStep step, Process process) '''
        // CONCAT INTO «step.target» IN «step.table.name»
        «step.table.name» = LTSRuntime.addComputedColumn(«step.table.name», "«step.target»", row -> {
            StringBuilder sb = new StringBuilder();
            «FOR part : step.parts»
                sb.append(String.valueOf(«expressionToJava(part.value)»));
            «ENDFOR»
            return sb.toString();
        });
    '''

    def private dispatch String generateStep(SplitStep step, Process process) '''
        // SPLIT «step.source»«IF step.delimiter !== null» BY "«step.delimiter»"«ELSE» AT «step.position»«ENDIF» INTO «step.results.join(", ")» IN «step.table.name»
        «step.table.name» = LTSRuntime.split(«step.table.name», "«step.source»",
            «IF step.delimiter !== null»"«step.delimiter»"«ELSE»null«ENDIF»,
            «step.position»,
            Arrays.asList(«step.results.map[r | '"' + r + '"'].join(", ")»)
        );
    '''

    def private dispatch String generateStep(ExtractStep step, Process process) '''
        // EXTRACT «step.source»«IF step.pattern !== null» MATCHING "«step.pattern»"«ELSE» FROM «step.start» TO «step.end»«ENDIF» INTO «step.target» IN «step.table.name»
        «step.table.name» = LTSRuntime.extract(«step.table.name», "«step.source»",
            «IF step.pattern !== null»"«step.pattern»", -1, -1«ELSE»null, «step.start», «step.end»«ENDIF»,
            "«step.target»"
        );
    '''

    def private dispatch String generateStep(CalculateColumnStep step, Process process) '''
        // CALCULATE «step.column» = «expressionToJava(step.expression)» IN «step.table.name»
        «step.table.name» = LTSRuntime.updateColumn(«step.table.name», "«step.column»", row ->
            «expressionToJava(step.expression)»
        );
    '''

    def private dispatch String generateStep(CustomFunctionStep step, Process process) '''
        // CALL «step.function»«IF !step.args.empty» WITH «step.args.join(", ")»«ENDIF»«IF step.result !== null» INTO «step.result»«ENDIF»
        «IF step.result !== null && step.table !== null»
            «step.table.name» = LTSRuntime.addComputedColumn(«step.table.name», "«step.result»", row ->
                CustomFunctions.call("«step.function»", row«IF !step.args.empty», «step.args.map[a|'"'+a+'"'].join(", ")»«ENDIF»)
            );
        «ELSE»
            CustomFunctions.call("«step.function»"«IF !step.args.empty», «step.args.map[a|'"'+a+'"'].join(", ")»«ENDIF»);
        «ENDIF»
    '''

    def private dispatch String generateStep(Step step, Process process) '''
        // UNKNOWN step type: «step.class.simpleName» – not yet implemented in generator
    '''

    // ─────────────────────────────────────────────────────────────────────────
    // Expression → Java
    // ─────────────────────────────────────────────────────────────────────────
    def private dispatch String expressionToJava(ColumnRef e)
        '''LTSRuntime.col(row, "«e.column»")'''

    def private dispatch String expressionToJava(StringLiteral e)
        '''"«e.value»"'''

    def private dispatch String expressionToJava(IntLiteral e)
        '''«e.value»'''

    def private dispatch String expressionToJava(DecimalLiteral e)
        '''«e.value»'''

    def private dispatch String expressionToJava(BoolLiteral e)
        '''«e.value.literal»'''

    def private dispatch String expressionToJava(NullLiteral e)
        '''null'''

    def private dispatch String expressionToJava(ParenExpression e)
        '''(«expressionToJava(e.inner)»)'''

    def private dispatch String expressionToJava(NotExpression e)
        '''!LTSRuntime.toBool(«expressionToJava(e.operand)»)'''

    def private dispatch String expressionToJava(OrExpression e)
        '''LTSRuntime.toBool(«expressionToJava(e.left)») || LTSRuntime.toBool(«expressionToJava(e.right)»)'''

    def private dispatch String expressionToJava(AndExpression e)
        '''LTSRuntime.toBool(«expressionToJava(e.left)») && LTSRuntime.toBool(«expressionToJava(e.right)»)'''

    def private dispatch String expressionToJava(ComparisonExpression e)
        '''LTSRuntime.compare(«expressionToJava(e.left)», "«e.operator»", «expressionToJava(e.right)»)'''

    def private dispatch String expressionToJava(AddExpression e)
        '''LTSRuntime.arithmetic(«expressionToJava(e.left)», "«e.operator»", «expressionToJava(e.right)»)'''

    def private dispatch String expressionToJava(MulExpression e)
        '''LTSRuntime.arithmetic(«expressionToJava(e.left)», "«e.operator»", «expressionToJava(e.right)»)'''

    def private dispatch String expressionToJava(Expression e)
        '''/* unsupported expression: «e.class.simpleName» */null'''

    // ─────────────────────────────────────────────────────────────────────────
    // Helper – find the config variable name for an InputTableDeclaration's source
    // ─────────────────────────────────────────────────────────────────────────
    def private String datasourceConfigName(TableDeclaration tbl, Process process) {
        if (tbl instanceof InputTableDeclaration)
            return tbl.source.name
        return tbl.name
    }

    // ─────────────────────────────────────────────────────────────────────────
    // TableSchema.java  – column name constants for refactoring-safe access
    // ─────────────────────────────────────────────────────────────────────────
    def private String generateSchemaEnum(Process process, String pkg) '''
        package «pkg»;

        /**
         * Column name constants for all tables in process «process.name».
         * Generated by the LTS DSL generator – DO NOT EDIT.
         */
        public final class TableSchema {
            private TableSchema() {}

            «FOR tbl : process.tables»
                /** Columns of table «tbl.name» */
                public static final class «tbl.name.toFirstUpper» {
                    «FOR col : columnsOfTable(tbl)»
                        public static final String «col.name.toUpperCase» = "«col.name»";
                    «ENDFOR»
                }
            «ENDFOR»
        }
    '''

    def private Iterable<ColumnDeclaration> columnsOfTable(TableDeclaration tbl) {
        switch tbl {
            InputTableDeclaration  : tbl.columns
            OutputTableDeclaration : tbl.columns
            EmptyTableDeclaration  : tbl.columns
            default                : #[]
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // CustomFunctions.java  – extensibility stub (user fills this in)
    // ─────────────────────────────────────────────────────────────────────────
    def private String generateCustomFunctionsStub(String pkg) '''
        package «pkg»;

        import java.util.Map;

        /**
         * Custom / extension functions for the LTS process.
         *
         * This file is generated ONCE and then left for the user to edit.
         * The generator will NOT overwrite this file on subsequent runs.
         *
         * Add your own static methods here and invoke them from the .lts model
         * using the 'call' step:
         *
         *   call "«pkg».CustomFunctions.myFunction"
         *       with col1, col2
         *       into result in myTable
         */
        public class CustomFunctions {

            /**
             * Generic dispatcher used by the generated code.
             * Delegates to a static method by its fully-qualified name.
             *
             * @param functionName  fully-qualified static method name
             * @param row           current row as a Map<String, Object>
             * @param columnNames   names of the columns passed as arguments
             */
            public static Object call(String functionName, Map<String, Object> row, String... columnNames) {
                // TODO: implement routing to your custom methods,
                // or replace calls in Main.java with direct method references.
                throw new UnsupportedOperationException(
                    "Custom function '" + functionName + "' is not implemented yet."
                );
            }

            // ──────────────────────────────────────────────────────────────────
            // Add your custom functions below this line.
            // Example:
            //
            // public static Object computeBonus(Map<String, Object> row, String... cols) {
            //     double salary = ((Number) row.get(cols[0])).doubleValue();
            //     return salary * 0.10;
            // }
            // ──────────────────────────────────────────────────────────────────
        }
    '''

    // ─────────────────────────────────────────────────────────────────────────
    // LTSRuntime.java  – always-present helper library
    // ─────────────────────────────────────────────────────────────────────────
    def private String generateRuntime(String pkg) '''
        package «pkg»;

        import java.io.*;
        import java.util.*;
        import java.util.function.*;
        import java.util.stream.*;

        /**
         * LTS Runtime support library.
         * Generated by the LTS DSL generator. DO NOT EDIT.
         *
         * Provides:
         *   - Table class  (rows as List<Map<String,Object>>)
         *   - CsvConfig, CsvLoader, CsvSaver
         *   - LogCollector
         *   - Transformation primitives
         */
        public final class LTSRuntime {

            // ── Public enum ──────────────────────────────────────────────────
            public enum AggFunction { SUM, AVG, MIN, MAX, COUNT }

            // ── Table ────────────────────────────────────────────────────────
            public static class Table {
                private final List<String>              columns;
                private final List<Map<String, Object>> rows;

                public Table(List<String> columns) {
                    this.columns = new ArrayList<>(columns);
                    this.rows    = new ArrayList<>();
                }
                public Table(List<String> columns, List<Map<String, Object>> rows) {
                    this.columns = new ArrayList<>(columns);
                    this.rows    = new ArrayList<>(rows);
                }
                public List<String> getColumns()              { return Collections.unmodifiableList(columns); }
                public List<Map<String, Object>> getRows()    { return Collections.unmodifiableList(rows); }
                public int rowCount()                         { return rows.size(); }
            }

            // ── CSV Config ───────────────────────────────────────────────────
            public static class CsvConfig {
                public final String  path;
                public final String  delimiter;
                public final boolean hasHeader;
                public CsvConfig(String path, String delimiter, boolean hasHeader) {
                    this.path      = path;
                    this.delimiter = delimiter;
                    this.hasHeader = hasHeader;
                }
            }

            // ── CsvLoader ────────────────────────────────────────────────────
            public static Table load(CsvConfig cfg) throws IOException {
                List<String>              cols = new ArrayList<>();
                List<Map<String, Object>> rows = new ArrayList<>();
                try (BufferedReader br = new BufferedReader(new FileReader(cfg.path))) {
                    String line;
                    boolean firstLine = true;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(cfg.delimiter, -1);
                        if (firstLine && cfg.hasHeader) {
                            cols.addAll(Arrays.asList(parts));
                            firstLine = false;
                        } else {
                            if (firstLine) {
                                for (int i = 0; i < parts.length; i++) cols.add("col" + i);
                                firstLine = false;
                            }
                            Map<String, Object> row = new LinkedHashMap<>();
                            for (int i = 0; i < cols.size(); i++)
                                row.put(cols.get(i), i < parts.length ? parts[i].trim() : null);
                            rows.add(row);
                        }
                    }
                }
                return new Table(cols, rows);
            }

            // ── CsvSaver ─────────────────────────────────────────────────────
            public static void save(Table table, CsvConfig cfg) throws IOException {
                new File(cfg.path).getParentFile().mkdirs();
                try (PrintWriter pw = new PrintWriter(new FileWriter(cfg.path))) {
                    if (cfg.hasHeader) pw.println(String.join(cfg.delimiter, table.getColumns()));
                    for (Map<String, Object> row : table.getRows()) {
                        pw.println(table.getColumns().stream()
                            .map(c -> String.valueOf(row.getOrDefault(c, "")))
                            .collect(Collectors.joining(cfg.delimiter)));
                    }
                }
            }

            // ── LogCollector ─────────────────────────────────────────────────
            public static class LogCollector {
                private final String         path;
                private final List<String>   entries = new ArrayList<>();
                public LogCollector(String path) { this.path = path; }
                public void info(String msg)     { entries.add("[INFO]    " + msg); }
                public void warning(String msg)  { entries.add("[WARNING] " + msg); }
                public void error(String msg)    { entries.add("[ERROR]   " + msg); }
                public void flush() throws IOException {
                    if (path == null) { entries.forEach(System.out::println); return; }
                    new File(path).getParentFile().mkdirs();
                    try (PrintWriter pw = new PrintWriter(new FileWriter(path, true))) {
                        entries.forEach(pw::println);
                    }
                    entries.clear();
                }
            }

            // ── Transformation primitives ─────────────────────────────────────

            /** Sort table by columns with corresponding orders ("ASC"/"DESC"). */
            public static Table sort(Table t, List<String> cols, List<String> orders) {
                List<Map<String,Object>> sorted = new ArrayList<>(t.getRows());
                sorted.sort((a, b) -> {
                    for (int i = 0; i < cols.size(); i++) {
                        String col = cols.get(i);
                        boolean asc = !"DESC".equalsIgnoreCase(orders.get(i));
                        Comparable ca = toComparable(a.get(col));
                        Comparable cb = toComparable(b.get(col));
                        @SuppressWarnings("unchecked")
                        int cmp = ca.compareTo(cb);
                        if (cmp != 0) return asc ? cmp : -cmp;
                    }
                    return 0;
                });
                return new Table(t.getColumns(), sorted);
            }

            /** Keep only rows for which the predicate returns true. */
            public static Table filter(Table t, Predicate<Map<String,Object>> pred) {
                return new Table(t.getColumns(),
                    t.getRows().stream().filter(pred).collect(Collectors.toList()));
            }

            /** Remove rows with duplicate values in the key columns (keeps first). */
            public static Table removeDuplicates(Table t, List<String> keys) {
                Set<String>               seen = new LinkedHashSet<>();
                List<Map<String,Object>>  kept = new ArrayList<>();
                for (Map<String,Object> row : t.getRows()) {
                    String k = keys.stream().map(c -> String.valueOf(row.get(c))).collect(Collectors.joining("|"));
                    if (seen.add(k)) kept.add(row);
                }
                return new Table(t.getColumns(), kept);
            }

            /** Drop columns from a table. */
            public static Table dropColumns(Table t, List<String> cols) {
                List<String> remaining = new ArrayList<>(t.getColumns());
                remaining.removeAll(cols);
                List<Map<String,Object>> rows = t.getRows().stream().map(row -> {
                    Map<String,Object> r = new LinkedHashMap<>(row);
                    cols.forEach(r::remove);
                    return r;
                }).collect(Collectors.toList());
                return new Table(remaining, rows);
            }

            /** Add a computed column to each row. */
            public static Table addComputedColumn(Table t, String colName,
                    Function<Map<String,Object>, Object> fn) {
                List<String> cols = new ArrayList<>(t.getColumns());
                if (!cols.contains(colName)) cols.add(colName);
                List<Map<String,Object>> rows = t.getRows().stream().map(row -> {
                    Map<String,Object> r = new LinkedHashMap<>(row);
                    r.put(colName, fn.apply(r));
                    return r;
                }).collect(Collectors.toList());
                return new Table(cols, rows);
            }

            /** Update an existing column with a computed value. */
            public static Table updateColumn(Table t, String colName,
                    Function<Map<String,Object>, Object> fn) {
                return addComputedColumn(t, colName, fn); // same implementation
            }

            /** Append all rows from src to dst. */
            public static Table appendRows(Table dst, Table src) {
                List<Map<String,Object>> rows = new ArrayList<>(dst.getRows());
                rows.addAll(src.getRows());
                return new Table(dst.getColumns(), rows);
            }

            /**
             * Join left with right on keys.
             * Optional: aggregate a column using an AggFunction before joining.
             */
            public static Table join(Table left, String leftKey,
                                     Table right, String rightKey,
                                     String aggCol, AggFunction aggFn) {
                // If aggregation requested: aggregate right first
                Table rightToJoin = (aggCol != null && aggFn != null)
                    ? group(right, List.of(rightKey), aggCol, aggFn)
                    : right;

                // Build lookup map from right
                Map<Object, Map<String,Object>> lookup = new LinkedHashMap<>();
                for (Map<String,Object> row : rightToJoin.getRows())
                    lookup.put(row.get(rightKey), row);

                // Merge columns
                List<String> newCols = new ArrayList<>(left.getColumns());
                for (String c : rightToJoin.getColumns())
                    if (!c.equals(rightKey) && !newCols.contains(c)) newCols.add(c);

                List<Map<String,Object>> rows = left.getRows().stream().map(leftRow -> {
                    Map<String,Object> r = new LinkedHashMap<>(leftRow);
                    Map<String,Object> rightRow = lookup.get(leftRow.get(leftKey));
                    if (rightRow != null)
                        rightRow.forEach((k, v) -> { if (!k.equals(rightKey)) r.put(k, v); });
                    return r;
                }).collect(Collectors.toList());
                return new Table(newCols, rows);
            }

            public static Table join(Table left, String leftKey, Table right, String rightKey) {
                return join(left, leftKey, right, rightKey, null, null);
            }

            /** Group and aggregate. */
            public static Table group(Table t, List<String> keys, String aggCol, AggFunction fn) {
                Map<String, List<Map<String,Object>>> groups = new LinkedHashMap<>();
                for (Map<String,Object> row : t.getRows()) {
                    String k = keys.stream().map(c -> String.valueOf(row.get(c))).collect(Collectors.joining("|"));
                    groups.computeIfAbsent(k, _k -> new ArrayList<>()).add(row);
                }
                List<Map<String,Object>> result = new ArrayList<>();
                for (Map.Entry<String, List<Map<String,Object>>> entry : groups.entrySet()) {
                    String[] keyParts = entry.getKey().split("\\|");
                    Map<String,Object> r = new LinkedHashMap<>();
                    for (int i = 0; i < keys.size(); i++) r.put(keys.get(i), keyParts[i]);
                    r.put(aggCol, aggregate(entry.getValue(), aggCol, fn));
                    result.add(r);
                }
                List<String> cols = new ArrayList<>(keys);
                if (!cols.contains(aggCol)) cols.add(aggCol);
                return new Table(cols, result);
            }

            /** VLOOKUP-style: fetch fetchCol from ref into target using key columns. */
            public static Table lookup(Table target, String targetKey,
                                       Table ref,    String refKey, String fetchCol) {
                Map<Object, Object> refMap = new HashMap<>();
                for (Map<String,Object> row : ref.getRows()) refMap.put(row.get(refKey), row.get(fetchCol));
                List<String> cols = new ArrayList<>(target.getColumns());
                if (!cols.contains(fetchCol)) cols.add(fetchCol);
                List<Map<String,Object>> rows = target.getRows().stream().map(row -> {
                    Map<String,Object> r = new LinkedHashMap<>(row);
                    r.put(fetchCol, refMap.get(row.get(targetKey)));
                    return r;
                }).collect(Collectors.toList());
                return new Table(cols, rows);
            }

            /** Split a string column into multiple target columns. */
            public static Table split(Table t, String src, String delimiter, int position,
                                      List<String> targets) {
                List<String> cols = new ArrayList<>(t.getColumns());
                targets.forEach(c -> { if (!cols.contains(c)) cols.add(c); });
                List<Map<String,Object>> rows = t.getRows().stream().map(row -> {
                    Map<String,Object> r = new LinkedHashMap<>(row);
                    String val = String.valueOf(row.getOrDefault(src, ""));
                    String[] parts = delimiter != null ? val.split(delimiter, targets.size())
                                                       : new String[]{ val.substring(0, Math.min(position, val.length())),
                                                                        val.substring(Math.min(position, val.length())) };
                    for (int i = 0; i < targets.size(); i++)
                        r.put(targets.get(i), i < parts.length ? parts[i] : "");
                    return r;
                }).collect(Collectors.toList());
                return new Table(cols, rows);
            }

            /** Extract substring from a string column into a target column. */
            public static Table extract(Table t, String src, String pattern,
                                        int start, int end, String target) {
                List<String> cols = new ArrayList<>(t.getColumns());
                if (!cols.contains(target)) cols.add(target);
                List<Map<String,Object>> rows = t.getRows().stream().map(row -> {
                    Map<String,Object> r = new LinkedHashMap<>(row);
                    String val = String.valueOf(row.getOrDefault(src, ""));
                    String extracted;
                    if (pattern != null) {
                        java.util.regex.Matcher m = java.util.regex.Pattern.compile(pattern).matcher(val);
                        extracted = m.find() ? m.group() : "";
                    } else {
                        extracted = val.substring(Math.min(start, val.length()), Math.min(end, val.length()));
                    }
                    r.put(target, extracted);
                    return r;
                }).collect(Collectors.toList());
                return new Table(cols, rows);
            }

            // ── Expression helpers ───────────────────────────────────────────

            /** Retrieve column value from a row (used in generated lambdas). */
            public static Object col(Map<String,Object> row, String colName) {
                return row.get(colName);
            }

            public static boolean toBool(Object o) {
                if (o instanceof Boolean) return (Boolean) o;
                if (o instanceof String)  return Boolean.parseBoolean((String) o);
                return o != null;
            }

            public static boolean compare(Object left, String op, Object right) {
                if (left == null || right == null) return false;
                double l = toDouble(left), r = toDouble(right);
                switch (op) {
                    case "==": return l == r;
                    case "!=": return l != r;
                    case "<":  return l < r;
                    case "<=": return l <= r;
                    case ">":  return l > r;
                    case ">=": return l >= r;
                }
                // String equality fallback
                return left.toString().equals(right.toString());
            }

            public static Object arithmetic(Object left, String op, Object right) {
                // Bug fix v2 (found during testing): treat null as 0.0 so that
                // employees/students with no matching join rows produce 0 rather
                // than a NullPointerException inside toDouble().
                if (left  == null) left  = 0.0;
                if (right == null) right = 0.0;
                double l = toDouble(left), r = toDouble(right);
                switch (op) {
                    case "+": return l + r;
                    case "-": return l - r;
                    case "*": return l * r;
                    case "/": return r != 0 ? l / r : null;
                }
                // String concatenation fallback
                if ("+".equals(op)) return String.valueOf(left) + String.valueOf(right);
                return null;
            }

            // ── Internal helpers ─────────────────────────────────────────────

            private static double toDouble(Object o) {
                if (o instanceof Number) return ((Number) o).doubleValue();
                try { return Double.parseDouble(o.toString()); } catch (Exception e) { return 0; }
            }

            @SuppressWarnings("unchecked")
            private static Comparable toComparable(Object o) {
                if (o instanceof Comparable) return (Comparable) o;
                return String.valueOf(o);
            }

            private static Object aggregate(List<Map<String,Object>> rows, String col, AggFunction fn) {
                DoubleStream stream = rows.stream().mapToDouble(r -> toDouble(r.get(col)));
                switch (fn) {
                    case SUM:   return stream.sum();
                    case AVG:   return stream.average().orElse(0);
                    case MIN:   return stream.min().orElse(0);
                    case MAX:   return stream.max().orElse(0);
                    case COUNT: return (double) rows.size();
                }
                return 0;
            }
        }
    '''
}
