package ltsdsl.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.errors.BaseQuickFixProvider;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;

public class ChecksTablesDeclaration_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public ChecksTablesDeclaration_NonTypesystemRule() {
  }
  public void applyRule(final SNode model, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    try {
      List<String> tableNames = ListSequence.fromList(new ArrayList<String>());
      for (final SNode tableNode : SLinkOperations.getChildren(model, LINKS.tables$jYuT)) {
        if (ListSequence.fromList(tableNames).contains(SPropertyOperations.getString(tableNode, PROPS.name$MnvL))) {
          {
            final MessageTarget errorTarget = new NodeMessageTarget();
            IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(tableNode, "table must have an unique name", "r:4b77ea8f-28f0-4d60-8745-f0af604b13e0(ltsdsl.typesystem)", "3553795587620365889", null, errorTarget);
          }
        } else {
          ListSequence.fromList(tableNames).addElement(SPropertyOperations.getString(tableNode, PROPS.name$MnvL));
        }

        int refCounter = 0;
        for (SNode step : SLinkOperations.getChildren(model, LINKS.steps$3Dv0)) {
          if (ListSequence.fromList(SNodeOperations.getReferences(step)).where((it) -> SLinkOperations.getTargetNode(it) == tableNode).count() > 0) {
            refCounter++;
          }
        }

        if (refCounter == 0) {
          {
            final MessageTarget errorTarget = new NodeMessageTarget();
            IErrorReporter _reporter_2309309498 = typeCheckingContext.reportWarning(tableNode, "unused table", "r:4b77ea8f-28f0-4d60-8745-f0af604b13e0(ltsdsl.typesystem)", "4612740934643873187", null, errorTarget);
            {
              BaseQuickFixProvider intentionProvider = new BaseQuickFixProvider("ltsdsl.typesystem.RemoveTableFromModel_QuickFix", "4612740934645279734", false);
              intentionProvider.putArgument("model", model);
              intentionProvider.putArgument("table", tableNode);
              _reporter_2309309498.addIntentionProvider(intentionProvider);
            }
          }
        }

        List<String> tableColumnNames = ListSequence.fromList(new ArrayList<String>());
        for (SNode columnNode : SLinkOperations.getChildren(tableNode, LINKS.columns$_HNP)) {
          if (ListSequence.fromList(tableColumnNames).contains(SPropertyOperations.getString(columnNode, PROPS.name$MnvL))) {
            {
              final MessageTarget errorTarget = new NodeMessageTarget();
              IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(columnNode, "column must have an unique name", "r:4b77ea8f-28f0-4d60-8745-f0af604b13e0(ltsdsl.typesystem)", "3553795587620407426", null, errorTarget);
            }
          } else {
            ListSequence.fromList(tableColumnNames).addElement(SPropertyOperations.getString(columnNode, PROPS.name$MnvL));
          }
        }
      }

    } catch (Exception e) {
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.Model$2$;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink steps$3Dv0 = MetaAdapterFactory.getContainmentLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5720b2a8aL, 0x3fa6e5f5720b7fa6L, "steps");
    /*package*/ static final SContainmentLink columns$_HNP = MetaAdapterFactory.getContainmentLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5720c3a0cL, 0x3fa6e5f5720ca3a7L, "columns");
    /*package*/ static final SContainmentLink tables$jYuT = MetaAdapterFactory.getContainmentLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5720b2a8aL, 0x27eaad871f8218b1L, "tables");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Model$2$ = MetaAdapterFactory.getConcept(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5720b2a8aL, "ltsdsl.structure.Model");
  }
}
