package ltsdsl.generator;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.TemplateModuleInterpreted2;
import jetbrains.mps.smodel.language.LanguageRegistry;
import jetbrains.mps.smodel.language.LanguageRuntime;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.module.SModuleReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import ltsdsl.generator.enums.QueriesGenerated;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SLanguage;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Arrays;

public class Generator extends TemplateModuleInterpreted2 {

  public Generator(LanguageRegistry languageRegistry, LanguageRuntime sourceLanguage, jetbrains.mps.smodel.Generator generator) {
    super(languageRegistry, sourceLanguage, generator);
  }

  @NotNull
  @Override
  public SModuleReference getModuleReference() {
    return PersistenceFacade.getInstance().createModuleReference("ec78a90d-8473-48d3-8912-b32646187e25(ltsdsl.generator)");
  }

  @Override
  protected void fillTemplateModels(TemplateModuleInterpreted2.TemplateModels models) {
    models.templates("r:f197530d-51ad-4216-956c-2f6cb0c55a22", QueriesGenerated.class);
    models.templates("r:7a125382-cddb-4c4f-8e8b-3d8533cae26c", ltsdsl.generator.main.QueriesGenerated.class);
    models.templates("r:e14ba563-14ee-40db-8a16-c94c24398270", ltsdsl.generator.steps.QueriesGenerated.class);
    models.templates("r:e233f196-0e07-4645-a64b-ebf9ce935438", ltsdsl.generator.steps.appendRows.QueriesGenerated.class);
    models.templates("r:efcec103-84b2-480a-91c5-bcd3ff0ec3cb", ltsdsl.generator.steps.filter.QueriesGenerated.class);
    models.templates("r:e2661cc8-007f-44b8-a96a-97c94b2ca103", ltsdsl.generator.steps.groupBy.QueriesGenerated.class);
    models.templates("r:f71ff201-c99b-4c1b-a27f-dc567abef317", ltsdsl.generator.steps.import_.QueriesGenerated.class);
    models.templates("r:a259c1a4-fe07-4459-93a8-28b00a8a5e65", ltsdsl.generator.steps.join.QueriesGenerated.class);
    models.templates("r:2f592e62-97d5-41e6-a11a-2a2c1fb0da89", ltsdsl.generator.steps.lookup.QueriesGenerated.class);
    models.templates("r:3520cf5b-cc77-4a2e-a334-4aefc1e39a44", ltsdsl.generator.steps.removeDuplicates.QueriesGenerated.class);
    models.templates("r:2c93a31c-d6e8-4726-a0df-dcd42a2f4169", ltsdsl.generator.steps.save.QueriesGenerated.class);
    models.templates("r:c01f992f-0133-4abe-af7a-193bd687a68c", ltsdsl.generator.steps.sort.QueriesGenerated.class);
    models.templates("r:a36eddf6-717d-4a20-ae38-593280be96dd", ltsdsl.generator.steps.strConcat.QueriesGenerated.class);
    models.templates("r:1c985b49-e2d4-4b0a-ac27-a43894ccaff0", ltsdsl.generator.tables.QueriesGenerated.class);
    models.templates("r:85bdddc6-187d-4220-9afc-b13727e2590d", ltsdsl.generator.utils.QueriesGenerated.class);
  }


  @Override
  public Collection<SLanguage> getTargetLanguages() {
    SLanguage[] rv = new SLanguage[5];
    rv[0] = MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
    rv[1] = MetaAdapterFactory.getLanguage(0xfd3920347849419dL, 0x907112563d152375L, "jetbrains.mps.baseLanguage.closures");
    rv[2] = MetaAdapterFactory.getLanguage(0xacfc188dd5d64598L, 0xb3706f4a983f05b2L, "jetbrains.mps.baseLanguage.methodReferences");
    rv[3] = MetaAdapterFactory.getLanguage(0x515552c7fcc04ab4L, 0x97892f3c49344e85L, "jetbrains.mps.baseLanguage.varVariable");
    rv[4] = MetaAdapterFactory.getLanguage(0xc7fb639fbe784307L, 0x89b0b5959c3fa8c8L, "jetbrains.mps.lang.text");
    return Arrays.asList(rv);
  }

}
