/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.validation;

import org.eclipse.xtext.validation.Check;
import excelltsmetamodel.ExcelltsmetamodelPackage;
import excelltsmetamodel.TableToSave;

import org.xtext.example.mydsl.validation.MyDslValidatorTableToSave;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class MyDslValidatorTableToSave extends AbstractMyDslValidator {

	public static final String TABLE_TO_SAVE_COLUMNS_NAMES_SIZE_MUST_EQUALS_NUMBER_OF_COLUMNS = "The columns names size of a table to save must equals the number of columns of the table";
	public static final String PATH_OF_TABLE_TO_SAVE_MUST_NOT_BE_BLANK = "The path of a table to save must not be blank.";
	public static final String TABLE_TO_SAVE_COLUMNS_NAMES_MUST_NOT_BE_BLANK = "The columns names of a table to save must not be blank.";
	
	/**
	 * Method to verify if the columns names size of a table to save equals the table's number of columns.
	 * 
	 * @param tableToSave The table to save to verify.
	 */
	@Check
	public void tableToSaveColumnsNamesSizeMustEqualsNumberOfColumns(TableToSave tableToSave) {
	    if(tableToSave.getColumnsNames().size() != tableToSave.getTable().getColumns().size()) {
	    	error(TABLE_TO_SAVE_COLUMNS_NAMES_SIZE_MUST_EQUALS_NUMBER_OF_COLUMNS, ExcelltsmetamodelPackage.Literals.TABLE_TO_SAVE__TABLE, TABLE_TO_SAVE_COLUMNS_NAMES_SIZE_MUST_EQUALS_NUMBER_OF_COLUMNS);
	    }
	}
	
	/**
	 * Method to verify if a path of a table to save is not blank.
	 * 
	 * @param tableToSave The table to save to verify.
	 */
	@Check
	public void tableToSavePathMustNotBeBlank(TableToSave tableToSave) {
	    if(tableToSave.getPath().isBlank()) {
	    	error(PATH_OF_TABLE_TO_SAVE_MUST_NOT_BE_BLANK, ExcelltsmetamodelPackage.Literals.TABLE_TO_SAVE__TABLE, PATH_OF_TABLE_TO_SAVE_MUST_NOT_BE_BLANK);
	    }
	}
	
	/**
	 * Method to verify if the columns names of a table to save are not blank.
	 * 
	 * @param tableToSave The table to save to verify.
	 */
	@Check
	public void tableToSaveColumnsNamesMustNotBeBlank(TableToSave tableToSave) {
		for(String rh : tableToSave.getColumnsNames()) {
		    if(rh.isBlank()) {
		    	error(TABLE_TO_SAVE_COLUMNS_NAMES_MUST_NOT_BE_BLANK, ExcelltsmetamodelPackage.Literals.TABLE_TO_SAVE__TABLE, TABLE_TO_SAVE_COLUMNS_NAMES_MUST_NOT_BE_BLANK);
		    }
		}
	}
}
