/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.validation;

import java.util.HashSet;
import java.util.Set;
import org.eclipse.xtext.validation.Check;
import excelltsmetamodel.Column;
import excelltsmetamodel.DataType;
import excelltsmetamodel.ExcelltsmetamodelPackage;
import excelltsmetamodel.Group;
import excelltsmetamodel.GroupOperationType;

import org.xtext.example.mydsl.validation.MyDslValidatorGroup;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class MyDslValidatorGroup extends AbstractMyDslValidator {

	public static final String GROUP_STEP_TABLES_MUST_BE_DIFFERENT = "Group step tables must be different.";
	public static final String GROUP_STEP_COLUMNS_MUST_BELONG_TO_THE_TABLE = "Group step columns must belong to the table.";
	public static final String GROUP_STEP_MUST_NOT_HAVE_REPEATED_GROUP_BY_COLUMNS = "Group step must not have repeated group by columns.";
	public static final String GROUP_STEP_RESULT_COLUMN_MUST_BELONG_TO_RESULT_TABLE_AND_BE_NUMBER = "Group step result column must belong to result table and be a number.";
	public static final String GROUP_STEP_GROUP_BY_COLUMN_DOES_NOT_MATCH_ANY_RESULT_TABLE_COLUMN = "At least one group step group by column does not match a result table column.";
	public static final String GROUP_STEP_OPERAND_COLUMN_MUST_BELONG_TO_THE_TABLE = "Group step operand column must belong to the table.";
	public static final String GROUP_STEP_OPERATION_TYPE_MUST_MATCH_OPERAND_TYPE = "Group step operand column must match operation type.";

	/**
	 * Method to verify if the group step is valid.
	 * 
	 * @param groupStep The group step to verify.
	 */
	@Check
	public void groupStepIsValid(Group groupStep) {
		if (groupStep.getTable().equals(groupStep.getResultTable())) {
			error(GROUP_STEP_TABLES_MUST_BE_DIFFERENT, ExcelltsmetamodelPackage.Literals.GROUP__RESULT_TABLE,
					GROUP_STEP_TABLES_MUST_BE_DIFFERENT);
		}
		for (Column column : groupStep.getGroupBy()) {
			if (!groupStep.getTable().getColumns().contains(column)) {
				error(GROUP_STEP_COLUMNS_MUST_BELONG_TO_THE_TABLE, ExcelltsmetamodelPackage.Literals.GROUP__GROUP_BY,
						GROUP_STEP_COLUMNS_MUST_BELONG_TO_THE_TABLE);
			}
		}
		Set<Column> uniqueColumns = new HashSet<>();
		for (Column column : groupStep.getGroupBy()) {
			if (!uniqueColumns.add(column)) {
				error(GROUP_STEP_MUST_NOT_HAVE_REPEATED_GROUP_BY_COLUMNS,
						ExcelltsmetamodelPackage.Literals.GROUP__GROUP_BY,
						GROUP_STEP_MUST_NOT_HAVE_REPEATED_GROUP_BY_COLUMNS);

			}
		}
		if (!groupStep.getResultTable().getColumns().contains(groupStep.getResultColumn())
				|| !groupStep.getResultColumn().getDataType().equals(DataType.NUMBER)) {
			error(GROUP_STEP_RESULT_COLUMN_MUST_BELONG_TO_RESULT_TABLE_AND_BE_NUMBER,
					ExcelltsmetamodelPackage.Literals.GROUP__RESULT_COLUMN,
					GROUP_STEP_RESULT_COLUMN_MUST_BELONG_TO_RESULT_TABLE_AND_BE_NUMBER);
		}
		for (int groupByColumnIndex = 0; groupByColumnIndex < groupStep.getGroupBy().size(); groupByColumnIndex++) {
			Column column1 = groupStep.getGroupBy().get(groupByColumnIndex);
			boolean flag = false;
			for (Column column2 : groupStep.getResultTable().getColumns()) {
				if (column1.getName().equals(column2.getName())
						&& column1.getDataType().equals(column2.getDataType())) {
					flag = true;
					break;
				}
			}
			if (flag == false) {
				error(GROUP_STEP_GROUP_BY_COLUMN_DOES_NOT_MATCH_ANY_RESULT_TABLE_COLUMN,
						ExcelltsmetamodelPackage.Literals.GROUP__GROUP_BY,
						GROUP_STEP_GROUP_BY_COLUMN_DOES_NOT_MATCH_ANY_RESULT_TABLE_COLUMN,
						groupStep.getResultTable().getName() + "," + column1.getName());
			}
		}
		if (!groupStep.getTable().getColumns().contains(groupStep.getOperandColumn())) {
			error(GROUP_STEP_OPERAND_COLUMN_MUST_BELONG_TO_THE_TABLE,
					ExcelltsmetamodelPackage.Literals.GROUP__OPERAND_COLUMN,
					GROUP_STEP_OPERAND_COLUMN_MUST_BELONG_TO_THE_TABLE);
		}
		if (!groupStep.getOperation().equals(GroupOperationType.COUNT)
				&& !groupStep.getOperandColumn().getDataType().equals(DataType.NUMBER)) {
			error(GROUP_STEP_OPERATION_TYPE_MUST_MATCH_OPERAND_TYPE,
					ExcelltsmetamodelPackage.Literals.GROUP__OPERAND_COLUMN,
					GROUP_STEP_OPERATION_TYPE_MUST_MATCH_OPERAND_TYPE);
		}
	}
}
