/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.validation;

import java.util.HashSet;
import java.util.Set;

import org.eclipse.xtext.validation.Check;

import excelltsmetamodel.Column;
import excelltsmetamodel.ExcelltsmetamodelPackage;
import excelltsmetamodel.Table;

import org.xtext.example.mydsl.validation.MyDslValidatorTable;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class MyDslValidatorTable extends AbstractMyDslValidator {

	public static final String COLUMNS_TABLES_NAMES_MUST_BE_ALL_DIFFERENT = "The names of the columns of the tables must be all different.";
	
	/**
	 * Method to verify if the table has columns with same names.
	 * 
	 * @param table The table to verify.
	 */
	@Check
	public void columnsTablesNamesMustBeAllDifferent(Table table) {
		Set<String> namesSet = new HashSet<>();
		for(Column tableColumn : table.getColumns()) {
			if(!namesSet.add(tableColumn.getName())) {
		    	error(COLUMNS_TABLES_NAMES_MUST_BE_ALL_DIFFERENT, ExcelltsmetamodelPackage.Literals.TABLE__COLUMNS, COLUMNS_TABLES_NAMES_MUST_BE_ALL_DIFFERENT);
			}
		}
	}
}
