/* Generated by Xtext. */
package org.example.lts.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class LtsUiModule extends AbstractLtsUiModule {
}
