/**
 * Generated by Xtext.
 */
package org.example.lts.lts;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Aggregate Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.lts.lts.AggregateOperation#getSource <em>Source</em>}</li>
 *   <li>{@link org.example.lts.lts.AggregateOperation#getTarget <em>Target</em>}</li>
 *   <li>{@link org.example.lts.lts.AggregateOperation#getKeys <em>Keys</em>}</li>
 *   <li>{@link org.example.lts.lts.AggregateOperation#getAggregations <em>Aggregations</em>}</li>
 * </ul>
 *
 * @see org.example.lts.lts.LtsPackage#getAggregateOperation()
 * @model
 * @generated
 */
public interface AggregateOperation extends Operation
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(TableDeclaration)
   * @see org.example.lts.lts.LtsPackage#getAggregateOperation_Source()
   * @model
   * @generated
   */
  TableDeclaration getSource();

  /**
   * Sets the value of the '{@link org.example.lts.lts.AggregateOperation#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(TableDeclaration value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(TableDeclaration)
   * @see org.example.lts.lts.LtsPackage#getAggregateOperation_Target()
   * @model
   * @generated
   */
  TableDeclaration getTarget();

  /**
   * Sets the value of the '{@link org.example.lts.lts.AggregateOperation#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(TableDeclaration value);

  /**
   * Returns the value of the '<em><b>Keys</b></em>' containment reference list.
   * The list contents are of type {@link org.example.lts.lts.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keys</em>' containment reference list.
   * @see org.example.lts.lts.LtsPackage#getAggregateOperation_Keys()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getKeys();

  /**
   * Returns the value of the '<em><b>Aggregations</b></em>' containment reference list.
   * The list contents are of type {@link org.example.lts.lts.ColumnAssignment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Aggregations</em>' containment reference list.
   * @see org.example.lts.lts.LtsPackage#getAggregateOperation_Aggregations()
   * @model containment="true"
   * @generated
   */
  EList<ColumnAssignment> getAggregations();

} // AggregateOperation
