/**
 * Generated by Xtext.
 */
package org.example.lts.lts;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>External Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.lts.lts.ExternalFunction#getParameters <em>Parameters</em>}</li>
 *   <li>{@link org.example.lts.lts.ExternalFunction#getReturnType <em>Return Type</em>}</li>
 *   <li>{@link org.example.lts.lts.ExternalFunction#getImplementation <em>Implementation</em>}</li>
 * </ul>
 *
 * @see org.example.lts.lts.LtsPackage#getExternalFunction()
 * @model
 * @generated
 */
public interface ExternalFunction extends Declaration
{
  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link org.example.lts.lts.Parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see org.example.lts.lts.LtsPackage#getExternalFunction_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParameters();

  /**
   * Returns the value of the '<em><b>Return Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.example.lts.lts.DataType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return Type</em>' attribute.
   * @see org.example.lts.lts.DataType
   * @see #setReturnType(DataType)
   * @see org.example.lts.lts.LtsPackage#getExternalFunction_ReturnType()
   * @model
   * @generated
   */
  DataType getReturnType();

  /**
   * Sets the value of the '{@link org.example.lts.lts.ExternalFunction#getReturnType <em>Return Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return Type</em>' attribute.
   * @see org.example.lts.lts.DataType
   * @see #getReturnType()
   * @generated
   */
  void setReturnType(DataType value);

  /**
   * Returns the value of the '<em><b>Implementation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Implementation</em>' attribute.
   * @see #setImplementation(String)
   * @see org.example.lts.lts.LtsPackage#getExternalFunction_Implementation()
   * @model
   * @generated
   */
  String getImplementation();

  /**
   * Sets the value of the '{@link org.example.lts.lts.ExternalFunction#getImplementation <em>Implementation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Implementation</em>' attribute.
   * @see #getImplementation()
   * @generated
   */
  void setImplementation(String value);

} // ExternalFunction
