/**
 * Generated by Xtext.
 */
package org.example.lts.lts;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Remove Column Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.lts.lts.RemoveColumnOperation#getColumns <em>Columns</em>}</li>
 * </ul>
 *
 * @see org.example.lts.lts.LtsPackage#getRemoveColumnOperation()
 * @model
 * @generated
 */
public interface RemoveColumnOperation extends Operation
{
  /**
   * Returns the value of the '<em><b>Columns</b></em>' containment reference list.
   * The list contents are of type {@link org.example.lts.lts.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Columns</em>' containment reference list.
   * @see org.example.lts.lts.LtsPackage#getRemoveColumnOperation_Columns()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getColumns();

} // RemoveColumnOperation
