/**
 * Generated by Xtext.
 */
package org.example.lts.lts;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sort Key</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.lts.lts.SortKey#getColumn <em>Column</em>}</li>
 *   <li>{@link org.example.lts.lts.SortKey#getDirection <em>Direction</em>}</li>
 * </ul>
 *
 * @see org.example.lts.lts.LtsPackage#getSortKey()
 * @model
 * @generated
 */
public interface SortKey extends EObject
{
  /**
   * Returns the value of the '<em><b>Column</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column</em>' containment reference.
   * @see #setColumn(Expression)
   * @see org.example.lts.lts.LtsPackage#getSortKey_Column()
   * @model containment="true"
   * @generated
   */
  Expression getColumn();

  /**
   * Sets the value of the '{@link org.example.lts.lts.SortKey#getColumn <em>Column</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Column</em>' containment reference.
   * @see #getColumn()
   * @generated
   */
  void setColumn(Expression value);

  /**
   * Returns the value of the '<em><b>Direction</b></em>' attribute.
   * The literals are from the enumeration {@link org.example.lts.lts.SortDirection}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direction</em>' attribute.
   * @see org.example.lts.lts.SortDirection
   * @see #setDirection(SortDirection)
   * @see org.example.lts.lts.LtsPackage#getSortKey_Direction()
   * @model
   * @generated
   */
  SortDirection getDirection();

  /**
   * Sets the value of the '{@link org.example.lts.lts.SortKey#getDirection <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direction</em>' attribute.
   * @see org.example.lts.lts.SortDirection
   * @see #getDirection()
   * @generated
   */
  void setDirection(SortDirection value);

} // SortKey
