/**
 * Generated by Xtext.
 */
package org.example.lts.lts.impl;

import org.eclipse.emf.ecore.EClass;

import org.example.lts.lts.LtsPackage;
import org.example.lts.lts.NullLiteral;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Null Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NullLiteralImpl extends ExpressionImpl implements NullLiteral
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NullLiteralImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LtsPackage.Literals.NULL_LITERAL;
  }

} //NullLiteralImpl
