/**
 * Generated by Xtext.
 */
package org.example.lts.lts.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.example.lts.lts.LogSink;
import org.example.lts.lts.LtsPackage;
import org.example.lts.lts.SaveLogOperation;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Save Log Operation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.lts.lts.impl.SaveLogOperationImpl#getLog <em>Log</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SaveLogOperationImpl extends OperationImpl implements SaveLogOperation
{
  /**
   * The cached value of the '{@link #getLog() <em>Log</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLog()
   * @generated
   * @ordered
   */
  protected LogSink log;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SaveLogOperationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LtsPackage.Literals.SAVE_LOG_OPERATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LogSink getLog()
  {
    if (log != null && log.eIsProxy())
    {
      InternalEObject oldLog = (InternalEObject)log;
      log = (LogSink)eResolveProxy(oldLog);
      if (log != oldLog)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, LtsPackage.SAVE_LOG_OPERATION__LOG, oldLog, log));
      }
    }
    return log;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LogSink basicGetLog()
  {
    return log;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLog(LogSink newLog)
  {
    LogSink oldLog = log;
    log = newLog;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LtsPackage.SAVE_LOG_OPERATION__LOG, oldLog, log));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LtsPackage.SAVE_LOG_OPERATION__LOG:
        if (resolve) return getLog();
        return basicGetLog();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LtsPackage.SAVE_LOG_OPERATION__LOG:
        setLog((LogSink)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LtsPackage.SAVE_LOG_OPERATION__LOG:
        setLog((LogSink)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LtsPackage.SAVE_LOG_OPERATION__LOG:
        return log != null;
    }
    return super.eIsSet(featureID);
  }

} //SaveLogOperationImpl
