package ltsdsl.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_FilterOperatorType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_FilterOperatorType() {
    super(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x527f6422c969074bL, "FilterOperatorType", "r:85f52e46-7a19-44f9-bf10-6677b89edd73(ltsdsl.structure)/5944580133723113291");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_EQUALS_0 = new EnumerationDescriptor.MemberDescriptor("EQUALS", "EQUALS", 0x527f6422c969074cL, "r:85f52e46-7a19-44f9-bf10-6677b89edd73(ltsdsl.structure)/5944580133723113292");
  private final EnumerationDescriptor.MemberDescriptor myMember_LESS_THAN_0 = new EnumerationDescriptor.MemberDescriptor("LESS_THAN", "LESS_THAN", 0x527f6422c969074eL, "r:85f52e46-7a19-44f9-bf10-6677b89edd73(ltsdsl.structure)/5944580133723113294");
  private final EnumerationDescriptor.MemberDescriptor myMember_GREATER_THAN_0 = new EnumerationDescriptor.MemberDescriptor("GREATER_THAN", "GREATER_THAN", 0x527f6422c9690751L, "r:85f52e46-7a19-44f9-bf10-6677b89edd73(ltsdsl.structure)/5944580133723113297");
  private final EnumerationDescriptor.MemberDescriptor myMember_LESS_OR_EQUALS_THAN_0 = new EnumerationDescriptor.MemberDescriptor("LESS_OR_EQUALS_THAN", "LESS_OR_EQUALS_THAN", 0x527f6422c9690753L, "r:85f52e46-7a19-44f9-bf10-6677b89edd73(ltsdsl.structure)/5944580133723113299");
  private final EnumerationDescriptor.MemberDescriptor myMember_GREATER_OR_EQUALS_THAN_0 = new EnumerationDescriptor.MemberDescriptor("GREATER_OR_EQUALS_THAN", "GREATER_OR_EQUALS_THAN", 0x527f6422c9690756L, "r:85f52e46-7a19-44f9-bf10-6677b89edd73(ltsdsl.structure)/5944580133723113302");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x527f6422c969074bL, 0x527f6422c969074cL, 0x527f6422c969074eL, 0x527f6422c9690751L, 0x527f6422c9690753L, 0x527f6422c9690756L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_EQUALS_0, myMember_LESS_THAN_0, myMember_GREATER_THAN_0, myMember_LESS_OR_EQUALS_THAN_0, myMember_GREATER_OR_EQUALS_THAN_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "EQUALS":
        return myMember_EQUALS_0;
      case "LESS_THAN":
        return myMember_LESS_THAN_0;
      case "GREATER_THAN":
        return myMember_GREATER_THAN_0;
      case "LESS_OR_EQUALS_THAN":
        return myMember_LESS_OR_EQUALS_THAN_0;
      case "GREATER_OR_EQUALS_THAN":
        return myMember_GREATER_OR_EQUALS_THAN_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
