package ltsdsl.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public class ChangeEnumValue_QuickFix extends QuickFix_Runtime {
  public ChangeEnumValue_QuickFix() {
    super(new SNodePointer("r:4b77ea8f-28f0-4d60-8745-f0af604b13e0(ltsdsl.typesystem)", "4917095607701503154"));
  }
  public String getDescription(SNode node) {
    return ((String) ChangeEnumValue_QuickFix.this.getField("description")[0]);
  }
  public void execute(SNode node) {
    if (SNodeOperations.isInstanceOf(((SNode) ChangeEnumValue_QuickFix.this.getField("node")[0]), CONCEPTS.Filter$tD)) {
      SNode step = ((SNode) ((SNode) ChangeEnumValue_QuickFix.this.getField("node")[0]));
      SPropertyOperations.setEnum(step, PROPS.operator$UR8u, SEnumOperations.getMemberForName(MetaAdapterFactory.getEnumeration(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x527f6422c969074bL, "ltsdsl.structure.FilterOperatorType"), ((String) ChangeEnumValue_QuickFix.this.getField("enumLiteral")[0])));
    } else if (SNodeOperations.isInstanceOf(((SNode) ChangeEnumValue_QuickFix.this.getField("node")[0]), CONCEPTS.Column$Ap)) {
      SNode column = ((SNode) ((SNode) ChangeEnumValue_QuickFix.this.getField("node")[0]));
      SPropertyOperations.setEnum(column, PROPS.dataType$Xb6z, SEnumOperations.getMemberForName(MetaAdapterFactory.getEnumeration(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5720c3a12L, "ltsdsl.structure.DataType"), ((String) ChangeEnumValue_QuickFix.this.getField("enumLiteral")[0])));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Filter$tD = MetaAdapterFactory.getConcept(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x527f6422c95c14a3L, "ltsdsl.structure.Filter");
    /*package*/ static final SConcept Column$Ap = MetaAdapterFactory.getConcept(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5720c3a0fL, "ltsdsl.structure.Column");
  }

  private static final class PROPS {
    /*package*/ static final SProperty operator$UR8u = MetaAdapterFactory.getProperty(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x527f6422c95c14a3L, 0x527f6422c969075bL, "operator");
    /*package*/ static final SProperty dataType$Xb6z = MetaAdapterFactory.getProperty(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5720c3a0fL, 0x3fa6e5f5720c3a1aL, "dataType");
  }
}
