package ltsdsl.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class ChecksStrManipulationSplitNode_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public ChecksStrManipulationSplitNode_NonTypesystemRule() {
  }
  public void applyRule(final SNode strManipulationSplit, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    try {
      if (SPropertyOperations.getString(strManipulationSplit, PROPS.delimter$XrKB).equals("null") && SPropertyOperations.getString(strManipulationSplit, PROPS.atCharIndex$XstE).equals("null")) {
        {
          final MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(strManipulationSplit, "insufficient params to perform operation", "r:4b77ea8f-28f0-4d60-8745-f0af604b13e0(ltsdsl.typesystem)", "3553795587623395995", null, errorTarget);
        }

      } else if (SPropertyOperations.getString(strManipulationSplit, PROPS.delimter$XrKB).equals("null")) {
        try {
          int atCharIndex = Integer.valueOf(SPropertyOperations.getString(strManipulationSplit, PROPS.atCharIndex$XstE));

          if (atCharIndex < 0) {
            {
              final MessageTarget errorTarget = new NodeMessageTarget();
              IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(strManipulationSplit, "indexes start at 0", "r:4b77ea8f-28f0-4d60-8745-f0af604b13e0(ltsdsl.typesystem)", "3553795587623418234", null, errorTarget);
            }
          }
        } catch (Exception e) {
          {
            final MessageTarget errorTarget = new NodeMessageTarget();
            IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(strManipulationSplit, "invalid param for atCharIndex", "r:4b77ea8f-28f0-4d60-8745-f0af604b13e0(ltsdsl.typesystem)", "3553795587623419656", null, errorTarget);
          }
        }
      } else if (!(SPropertyOperations.getString(strManipulationSplit, PROPS.delimter$XrKB).equals("null")) && !(SPropertyOperations.getString(strManipulationSplit, PROPS.atCharIndex$XstE).equals("null"))) {
        {
          final MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(strManipulationSplit, "unclear operation for given params: use 'null' to exclude a rule", "r:4b77ea8f-28f0-4d60-8745-f0af604b13e0(ltsdsl.typesystem)", "3553795587623401147", null, errorTarget);
        }
      }

    } catch (Exception e) {
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.StrManipulationSplit$kQ;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class PROPS {
    /*package*/ static final SProperty atCharIndex$XstE = MetaAdapterFactory.getProperty(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x31519e4214a2fa5eL, 0x31519e4214a2fa65L, "atCharIndex");
    /*package*/ static final SProperty delimter$XrKB = MetaAdapterFactory.getProperty(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x31519e4214a2fa5eL, 0x31519e4214a2fa62L, "delimter");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept StrManipulationSplit$kQ = MetaAdapterFactory.getConcept(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x31519e4214a2fa5eL, "ltsdsl.structure.StrManipulationSplit");
  }
}
