package ltsdsl.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.scope.ListScope;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SProperty;

public class StrManipulationSplit_Constraints extends BaseConstraintsDescriptor {
  public StrManipulationSplit_Constraints() {
    super(CONCEPTS.StrManipulationSplit$kQ);
  }

  @Override
  protected Map<SReferenceLink, ReferenceConstraintsDescriptor> getSpecifiedReferences() {
    BaseReferenceConstraintsDescriptor d0 = new BaseReferenceConstraintsDescriptor(LINKS.source$Xri_, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:7544216e-c3d5-4a4d-a97b-6a83591122eb(ltsdsl.constraints)", "3553795587623289106");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            return ListScope.forNamedElements(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.table$FL$X), LINKS.columns$_HNP)).where((it) -> SPropertyOperations.getEnum(it, PROPS.dataType$Xb6z).equals(SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5720c3a12L, "ltsdsl.structure.DataType"), 0x3fa6e5f5720c3a13L, "TEXT"))));
          }
        };
      }
    };
    BaseReferenceConstraintsDescriptor d1 = new BaseReferenceConstraintsDescriptor(LINKS.resultColumnA$ZVjf, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:7544216e-c3d5-4a4d-a97b-6a83591122eb(ltsdsl.constraints)", "3553795587623304518");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            return ListScope.forNamedElements(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.resultTable$ZUPd), LINKS.columns$_HNP)).where((it) -> SPropertyOperations.getEnum(it, PROPS.dataType$Xb6z).equals(SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5720c3a12L, "ltsdsl.structure.DataType"), 0x3fa6e5f5720c3a13L, "TEXT"))));
          }
        };
      }
    };
    BaseReferenceConstraintsDescriptor d2 = new BaseReferenceConstraintsDescriptor(LINKS.resultColumnB$ZW0i, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:7544216e-c3d5-4a4d-a97b-6a83591122eb(ltsdsl.constraints)", "3553795587623321398");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            return ListScope.forNamedElements(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.resultTable$ZUPd), LINKS.columns$_HNP)).where((it) -> it != SLinkOperations.getTarget(_context.getReferenceNode(), LINKS.resultColumnA$ZVjf) && SPropertyOperations.getEnum(it, PROPS.dataType$Xb6z).equals(SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5720c3a12L, "ltsdsl.structure.DataType"), 0x3fa6e5f5720c3a13L, "TEXT"))));
          }
        };
      }
    };
    Map<SReferenceLink, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLink, ReferenceConstraintsDescriptor>();
    references.put(d0.getReference(), d0);
    references.put(d1.getReference(), d1);
    references.put(d2.getReference(), d2);
    return references;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept StrManipulationSplit$kQ = MetaAdapterFactory.getConcept(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x31519e4214a2fa5eL, "ltsdsl.structure.StrManipulationSplit");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink source$Xri_ = MetaAdapterFactory.getReferenceLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x31519e4214a2fa5eL, 0x31519e4214a2fa60L, "source");
    /*package*/ static final SReferenceLink table$FL$X = MetaAdapterFactory.getReferenceLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x5fd6b164554de2d3L, 0x5fd6b164554de2d8L, "table");
    /*package*/ static final SContainmentLink columns$_HNP = MetaAdapterFactory.getContainmentLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5720c3a0cL, 0x3fa6e5f5720ca3a7L, "columns");
    /*package*/ static final SReferenceLink resultColumnA$ZVjf = MetaAdapterFactory.getReferenceLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x31519e4214a2fa5eL, 0x31519e4214a2fa6aL, "resultColumnA");
    /*package*/ static final SReferenceLink resultTable$ZUPd = MetaAdapterFactory.getReferenceLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x31519e4214a2fa5eL, 0x31519e4214a2fa68L, "resultTable");
    /*package*/ static final SReferenceLink resultColumnB$ZW0i = MetaAdapterFactory.getReferenceLink(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x31519e4214a2fa5eL, 0x31519e4214a2fa6dL, "resultColumnB");
  }

  private static final class PROPS {
    /*package*/ static final SProperty dataType$Xb6z = MetaAdapterFactory.getProperty(0x1f55f171d454489bL, 0xbbc22455ab34472fL, 0x3fa6e5f5720c3a0fL, 0x3fa6e5f5720c3a1aL, "dataType");
  }
}
